### ISSUE TITLE
Bug: Phone gets very hot when using the app

### ISSUE THREAD

**Issue by AsyncMoksha** [TortugaPower/BookPlayer#1000]
## Environment

 - OS Version: iOS 16.6
 - App Version: 5.0.8-7

## Description

1. Phone gets abnormally hot after using BookPlayer for 30+ minutes
2. Using BookPlayer for 1.5 hrs consumes about 50% of my phone battery. Usually 50% battery can last through the entire day without using BookPlayer

## Steps to reproduce the behavior
0. Change to these settings in your BookPlayer (this problem happens with and without these changes, but I made these changes after experiencing this problem hoping to resolve the problem without success):
  a. Player Controls -> Opens: Change to "Bookmarks"
  b. Disable autolock: on
  c. iCloud backup -> Include book files: off
  d. The rest of the settings use the defaults
2. Create a playlist, add ~2,000 m4b files to it, each of size ~15MB
3. Play from any file
4. Turn off the phone screen. Play for 1.5 hrs
5. Observe the temperature of the phone and the battery consumption

## Notes
I guess a key variant here is the ~2,000 files in the playlist. But unless the app is doing something it's not supposed to do, the amount of files within a single list should not play a factor into the computation load (hence battery consumption) of the app during the playback of a single file within it.

**Comment by GianniCarlo** [comment]
@AsyncMoksha I think the ~2000 ~15MB files sheds more light on the other issue #843, right now, whenever the currently playing book changes completed-percentage, we have to recalculate the parent folder(s) percentage as well to accurately show the folder progress

<img width="520" alt="Screenshot 2023-09-07 at 18 16 30" src="https://github.com/TortugaPower/BookPlayer/assets/14112819/3a53bab9-db63-44b6-bfb6-8c5985ef17d9">

I think for folders with small files (i.e. percentage triggers more often) in large quantities, this could definitely be the culprit, as after fetching the items, I'm reducing the array to get the total value, I'm pretty sure that I can avoid this with a better and performant `NSExpression` that outputs the desired value instead of the array 🤔. Any input on the logic is welcomed

<img width="872" alt="Screenshot 2023-09-07 at 18 20 44" src="https://github.com/TortugaPower/BookPlayer/assets/14112819/de6b02a6-5c2f-4bd7-8bb3-e5b8e8eec0a7">

I'll look into updating this function and writing some stress tests for it

**Comment by GianniCarlo** [comment]
@AsyncMoksha there's a new beta live with a fix / improvement for the issue I mentioned, please let me know how it goes with the battery health (link to join: https://testflight.apple.com/join/xLDneJXN

**Comment by AsyncMoksha** [comment]
Hey @GianniCarlo , thanks a lot for fixing this. I went through the steps up until "Install" in TestFlight, but it warns:

> "Do you want to replace the current app version with the test version? You may lose the app's data"

As you may have expected, I've spent quite a bit of time dragging those ~2,000 files into the app from my laptop, I'd be hesitant to do that again. Do you think I'd lose these files if I were to install from TestFlight? Alternatively, once it's released officially, I can update the version through App Store and update you here.

**Comment by AsyncMoksha** [comment]
Hi @GianniCarlo, would you mind releasing the new version to App Store? I can test and report back once it's released. Thank you.

**Comment by GianniCarlo** [comment]
@AsyncMoksha v5.0.10 is now live in the AppStore, let me know how it goes, also don't forget to disable crash reports on Settings → Privacy section

**Comment by AsyncMoksha** [comment]
Thank you Gianni, will do. For my edification, why disable crash reports?

**Comment by AsyncMoksha** [comment]
Got it, just set it up. I'll test it out these days and will report back.

**Comment by fbphysik** [comment]
Same problem here, using the current version for Bookplayer and also the current iOS version. The iPhone gets very hot and the battery drains very fast. I disabled the crash reports as suggested but that didn't help.

**Comment by AsyncMoksha** [comment]
Hey @GianniCarlo and @fbphysik , thought I'd make an update here. I've been testing out the new version these days, and what I've observed is that the temperature control has gotten a lot better than the previous version, but the phone still gets pretty warm after about 1 hour of play time compared to say the YouTube app under similar conditions (sitting on a wooden floor so ventilation isn't an issue).

Thank you for making this improvement Gianni, I'm grateful (just made another donation in the app). I'm sure there are further room to improve here, but for now I'm very happy that my phone is no longer burning hot after using the app.

**Comment by fbphysik** [comment]
> Same problem here, using the current version for Bookplayer and also the current iOS version. The iPhone gets very hot and the battery drains very fast. I disabled the crash reports as suggested but that didn't help.

I did some checks: the library on my phone consists of several folders, one for each audiobook. Each folder contains a list of mp3's, one for each chapter. If I remove all audiobook folders except the one I'm currently listening to, the excess battery drain vanishes completely.

By the way: Is there a way to refresh the library database? The audiobooks which I removed using the files app are still visible in the library.

**Comment by GianniCarlo** [comment]
Thanks for your support @AsyncMoksha 🥳 , I'm glad that the updates to the folder progress calculation did have an effect. I've been thinking about what the next step could be for performance improvement, and I think we can check if the app is on the background, and on that scenario we don't perform any progress calculation for the folders and just queue it for either when the app returns to the foreground, or when playback is paused 🤔, I have to think a little more on the implementation details, but that's the overall idea.

> If I remove all audiobook folders except the one I'm currently listening to, the excess battery drain vanishes completely.

@fbphysik yes having nested folders with a large list of mp3s is definitely the culprit here, as when the progress percentage changes for the single mp3 (which are usually short, and is compounded when listening speed is greater than 1x), the app needs to recalculate the progress percentage for the containing folder, and that triggers the reload all the way up to the root of the library to accurately show the completion progress for each of the containing folders all the way down to the mp3. I think by deferring the progress calculation when the app is on the background so we just calculate the progress once when the app is back on the foreground, we shouldn't have this problem anymore

> By the way: Is there a way to refresh the library database? The audiobooks which I removed using the files app are still visible in the library.

Hmmmm the only time we refresh the library database is if a database structure migration fails, so it's worst case scenario to recover at least the user's library (while progress is lost). But in your case I think you can bulk select the items from your library and delete them in-app with the floating quick-actions

**Comment by AsyncMoksha** [comment]
I think that sounds like a great idea, Gianni. I stopped using BookPlayer for about a week after I last tested it and resumed using it today. I played it for an hour and my phone got very hot again. Looks like I spoke too early about the issue being largely mitigated. Not sure why this level of temperature gain did not show up a week ago when I tested. On Oct 21, 2023, at 9:51 AM, Gianni Carlo ***@***.***> wrote:﻿
Thanks for your support @AsyncMoksha 🥳 , I'm glad that the updates to the folder progress calculation did have an effect. I've been thinking about what the next step could be for performance improvement, and I think we can check if the app is on the background, and on that scenario we don't perform any progress calculation for the folders and just queue it for either when the app returns to the foreground, or when playback is paused 🤔, I have to think a little more on the implementation details, but that's the overall idea.

If I remove all audiobook folders except the one I'm currently listening to, the excess battery drain vanishes completely.

@fbphysik yes having nested folders with a large list of mp3s is definitely the culprit here, as when the progress percentage changes for the single mp3 (which are usually short, and is compounded when listening speed is greater than 1x), the app needs to recalculate the progress percentage for the containing folder, and that triggers the reload all the way up to the root of the library to accurately show the completion progress for each of the containing folders all the way down to the mp3. I think by deferring the progress calculation when the app is on the background so we just calculate the progress once when the app is back on the foreground, we shouldn't have this problem anymore

By the way: Is there a way to refresh the library database? The audiobooks which I removed using the files app are still visible in the library.

Hmmmm the only time we refresh the library database is if a database structure migration fails, so it's worst case scenario to recover at least the user's library (while progress is lost). But in your case I think you can bulk select the items from your library and delete them in-app with the floating quick-actions

**Comment by GianniCarlo** [comment]
There's a new beta live with a possible fix to this issue, it will most likely be released over the next weekend to the AppStore too, let me know if anyone tries out the beta

**Comment by AsyncMoksha** [comment]
Awesome. Thank you GianniOn Nov 12, 2023, at 11:00 AM, Gianni Carlo ***@***.***> wrote:﻿
There's a new beta live with a possible fix to this issue, it will most likely be released over the next weekend to the AppStore too, let me know if anyone tries out the beta

**Comment by GianniCarlo** [comment]
@AsyncMoksha @fbphysik v5.1.0 is live now with a possible fix for this, please let me know how it goes

**Comment by fbphysik** [comment]
It's looking good. I copied back all of my folders and the battery usage didn't increase at all. It was only one check for 30 minutes yesterday night but the problem seems to have vanished completely.
Thank you very much for your work!

**Comment by GianniCarlo** [comment]
This is great news 🎉!! thanks @fbphysik and @AsyncMoksha for the confirmation, let us know if there are any other issues

**Comment by fattaylor** [comment]
Hello @GianniCarlo  

* iOS Version: 17.4.1
* App Version: 5.2.6-44
* Phone: iPhone 14 Pro

I'm afraid this issue is back now.  
The app drains the battery very quickly while the phone gets pretty warm.

**Comment by GianniCarlo** [comment]
@fattaylor this could be related to https://github.com/TortugaPower/BookPlayer/pull/1123 which will be released in v5.2.7 as soon as it gets past Apple's review . I'll ping back when it's live on the AppStore

**Comment by GianniCarlo** [comment]
@fattaylor v5.2.7 is now live on the AppStore, please let me know if the issue still persists on that version 🙏🏻

**Comment by fattaylor** [comment]
> @fattaylor v5.2.7 is now live on the AppStore, please let me know if the issue still persists on that version 🙏🏻

Thank you very much for working on this @GianniCarlo !  
Unfortunately I am still facing the same issue in v5.2.7
The App drains about 1% of the battery per minute (on an iPhone 14 Pro), and the phone gets hot.

**Comment by fattaylor** [comment]
> > @fattaylor v5.2.7 is now live on the AppStore, please let me know if the issue still persists on that version 🙏🏻
> 
> Thank you very much for working on this @GianniCarlo ! Unfortunately I am still facing the same issue in v5.2.7 The App drains about 1% of the battery per minute (on an iPhone 14 Pro), and the phone gets hot.

Hello @GianniCarlo  

Small update about this issue: it does not seem to be happening when playing audiobooks in __mp3__ format.
But the overheating and battery draining are still happening when playing audiobooks in __m4b__ format.
