### ISSUE TITLE
Bug: Error AVPlayerItem The Operation could not be completed

### ISSUE THREAD

**Issue by elric667** [TortugaPower/BookPlayer#1035]
## Environment

 - OS Version: 17.1 (21B80)
 - App Version: 5.0.10

## Description

I will lose audio and the app will not function when I force close the ap and launch again I get this error when it comes back and I kill it and again it might start..

## Steps to reproduce the behavior
1. This problem happens randomly 
2. Audio must fail to run force close the app
3. then launch it again
4. get this error
![IMG_3921](https://github.com/TortugaPower/BookPlayer/assets/25038394/1d601b6f-bc38-4e65-bdd7-f686fa9e9441)

**Comment by GianniCarlo** [comment]
Thanks for reporting this issue @elric667 , this one was fixed in #1032 and will be included in the next app version 5.1.0, this week I'll put up a beta for it, and ping this ticket

For context, the underlying asset when loading the file metadata can crash the media services of the OS, triggering a reset of these services, and on which every audio app must listen to this event to recreate all the audio elements so the user can restart playback (the bug was that I wasn't clearing properly all the data)

**Comment by GianniCarlo** [comment]
v5.1.0 is out now, please let me know if the issue persists
