### ISSUE TITLE
Library: Enable Search

### ISSUE THREAD

**Issue by pichfl** [TortugaPower/BookPlayer#105]
Extracted from #46

**Comment by pichfl** [comment]
Moving this to a later milestone, we need features for later 😄

**Comment by GianniCarlo** [comment]
moving this back to later, I want to focus on the watch app

**Comment by clint015** [comment]
I'm interested in tackling this one. Few questions:

- Do you want search to simply filter the library list based on the results (as opposed to using a search results controller with a different layout)?
- The `searchController` property on `UINavigationItem` was introduced in iOS 11. Do you have a preferred approach for adding the search bar for iOS 10 (such as a floating search bar attached to the top of the tableview or adding the search bar to the tableview header view)?
- Since the app simply fetches all items from CoreData and populates an array with them, I'm assuming a search function would just filter this array post-fetch, as opposed to performing the search as part of a CoreData fetch request?

**Comment by GianniCarlo** [comment]
That would be great @clint015 !
- Regarding how the filtered results and the search bar should look, I'll defer to @pichfl . 
- Regarding the searchcontroller and the property on `UINavigationItem` it should be fine to go that way, we should also up the minimum version to iOS 11 as well (we've discussed this before and now should be a good time to do it)
- Regarding filtering post-fetch, yup, since we got all those things in memory, we might as well filter those instead of doing a coredata fetch request

**Comment by pichfl** [comment]
I'd use the same item layout for the results for now. If possible it would be neat to highlight the search term in the labels of the cell, but it's not necessary.

After discussion with @GianniCarlo I think we can move to iOS 11 as a baseline, which supports devices that were released >6 years ago, giving us an opportunity to use a more modern UI. 

I'm not sure about the filtering, does this find items inside Playlists as well? If yes, I'm totally fine with that approach.

**Comment by clint015** [comment]
OK. I'll start down this road and PR something in the next few weeks that you all can take a look at.

**Comment by universvm** [comment]
Hi @GianniCarlo , It seems from #856 that this feature was implemented + merged. However I see this issue is still opened and I don't think I can access the feature on iPad. 

Am I doing something wrong?

**Comment by GianniCarlo** [comment]
Hey @universvm , yeah I left the issue open because we haven't released the new version yet, we're gearing toward release, I'll start linking all the open tickets to the [release PR](https://github.com/TortugaPower/BookPlayer/pull/908), and close them all once the release is live

**Comment by universvm** [comment]
Ah apologies, I thought I my app hadn't updated! Glad to see lots of features coming up :)

**Comment by GianniCarlo** [comment]
v5.0.0 is finally released and includes this change 🙌
