### ISSUE TITLE
Bug: Can'tt see chapters in the chapter icon while playing a book

### ISSUE THREAD

**Issue by Guy27** [TortugaPower/BookPlayer#1065]
Loaded a folder to the app with 100 files, each file is a chapters
the app shows it as one book, which is great, clicking on it start playing the book / continue where i left off
in the player i can use the << >> arrows to move between chapters, but the chapters icon for some reason only shows 1 chapter (it's always the current one), why not show all the available chapters? what's the point of the button in this case? i get that if the file itself was a huge file with chapters, they would have been there, but in the case where each file is a chapter you could still show it there.

**Comment by GianniCarlo** [comment]
@Guy27 are you using the Volumes feature? after importing the folder, you can swipe left on it, or select it, and from the Options menu, use the 'Combine into Volume' option, so the app treats that folder as a single book, otherwise, the app handles each file like if it were a single book (and if there's any encoded chapter info, it displays that). One thing to note is that a Volume can only be formed from a folder containing only books, if there are nested folders inside, then the option will be disabled

FYI we keep track of progress for volumes separately from books (for books the progress is tied to the single item, while on volumes the progress is tied to the converted folder), so if going from a list of books to a volume, then you'd have to manually jump the first time to where you were in the previous format

**Comment by Guy27** [comment]
Hi Gianni,
A couple of things:
1. I've been using your app for years now, it's amazing, thank you for keeping it so well maintained and simple
2. Combine to volume is great! I wasn't aware of this feature and it did the trick
3. A follow up bug, once I combined to volume it i lost my progress and the book started from chapter 1, it will be better to remember the position

**Comment by GianniCarlo** [comment]
Thanks @Guy27 😁, regarding the progress, that's what I meant on the last part of my message, that we keep track of the progress separately and you would have to manually jump the first time, and then it will continue to work like any other book. We cannot automatically set the progress when it's first converted, as the individual chapters could have the progress set, and we would have to choose between them, so it's easier for the user to handle that, and avoid any unintentional jump if the book was started prior to combining into volumes

I'll close the issue but feel free to follow up if anything else comes up regarding this topic
