### ISSUE TITLE
Won’t install on iPadOS 14.4

### ISSUE THREAD

**Issue by Glormond** [TortugaPower/BookPlayer#1119]
## Environment

 - iPadOS Version: [14.4]
 - App Version: [5.2.6]

## Description

For the last 2-3 months I was unable to update BookPlayer app on my iPad 10.2 (8th gen 32gb), because whenever I tried to hit update button, it would download and then reverted to previous state. Yesterday I decided to uninstall app and install it again. But now I can’t install it back for the same reason: I hit install, it begins downloading, then installing and reverts back to uninstalled, although the greyed out icon appears on Home Screen after than. Long tab gives only the option to cancel. If tap on the icon, it attempts to install it and reverts back to grey.

Note: this isn’t space or Wi-Fi issue. I have approximately 7 Gb of free space on my device. All other apps update fine. No problem with installing other apps either. I already tried all of the general recommendations you can find on the web on similar issue, but still no luck. This is the only app affected by this issue on my device.

I do not update iPadOS for newer version to keep battery going. But still BookPlayer, according to information in AppStore, supports any version starting from 14.0, so it should be working.

## Steps to reproduce the behavior
1. Go to App Store
2. Hit install BookPlayer

Thank you! I’d appreciate solving this issue, I really enjoy using your app.

**Comment by GianniCarlo** [comment]
Hi @Glormond ! we don't really have control outside of the app, or at the installation point, and yes, if you device supports 14.0, then you should be able to install it. You can try turning off the device and back on, maybe something got stuck at the OS level? the other option is to install a beta version of the app via Apple's TestFlight, which right now the latest beta is the same as what we have on the AppStore

Let me know if rebooting the device works, otherwise you can join the beta via this link: https://testflight.apple.com/join/xLDneJXN

**Comment by Glormond** [comment]
Thank you for your feedback. Reboot did not help unfortunately. 

I joined TestFlight right away and tried installing beta version, but still failed (photo and video included below). It seems like the only option is to do full reset to eliminate whatever got stuck at OS level.

https://github.com/TortugaPower/BookPlayer/assets/133909859/12959aa7-c9ed-4f9b-80a2-165c12964f4d

![IMG_0210](https://github.com/TortugaPower/BookPlayer/assets/133909859/c64216af-7753-4007-9f07-02b39b9f94cc)
