### ISSUE TITLE
BookPlayer Pro lifetime licence

### ISSUE THREAD

**Issue by Kganart** [TortugaPower/BookPlayer#1229]
Hey! Great app and amazing work!

I would love to see the introduction of a lifetime licence for this app along side monthly subscriptions.

I want to support but am not a big of monthly subscriptions, I know the price of lifetime licence would and should be higher and that would suit me and possibly others more.

Appreciate the work yous do and wish you all the best!

**Comment by GianniCarlo** [comment]
Hi @Kganart thanks for the kind words! 

Regarding a lifetime license, I don't really know how to put a fair price on that, as the major cost on our servers, is actually just storing the audiobook files, which tend to be pretty large. And there's also the possibility of a lifetime-access user just not using the app after 2-3 months, and we would still have to pay for storing their files in perpetuity, unless they delete their account, which seems like something not everyone would do (or at least there wouldn't be any incentive to delete something you paid for a lifetime access to)

I think because of the fear of that last point, I stopped considering a lifetime license (at least for now), as I fear that costs could balloon up, and not even from active users at some future point

**Comment by TheTural** [comment]
@GianniCarlo How about an option for "I don't want the cloud services, please no ads for them"? If I could pay a flat fee to not have an ad pop up every few days for a service I don't want, I'd do that.

Gotten the ad three times now. Each time, even if I sit through the timer, it can't be dismissed and I have to force close the app and reopen it to get it back to a usable state. I love this app for its straightforward functionality, but I don't need more than that and would be happy to support in a way that doesn't leverage excess features I don't need.

![Image](https://github.com/user-attachments/assets/c9837d89-53a7-411c-93a2-b4b3f8b6788f)

**Comment by GianniCarlo** [comment]
Hi @TheTural ! Thanks for the feedback, I actually updated the text of the ad based on feedback, to reflect that any type of donation gets rid of it, as it's only meant for users of 6+ months that haven't contributed to the app in its lifetime (if anyone is seeing this and have donated or subscribed and cancelled before / contributed with code or translations please reach out to me to either my email gcarlo89@hotmail.com or to support and I can sort it out).

I need to update the text further to make it clear that the pop up goes away like that, and also remove that timer thing, I'm just near completing something for the watch, and ironing out some performance issues with SwiftUI, before continuing with that

**Comment by slyhawkdiver** [comment]
Thanks for this awesome app! Came here looking to report the same instance mentioned above - perfect timing, seems like! I do not like to have subscription billing either, but I will gladly donate now that I have this information. 

I agree it’s a great idea to make the text more clear, as I also assumed the lack of a way to close the prompt, in conjunction with there being a “timer bar”, was due to a bug or issue
