### ISSUE TITLE
Support for bookmarks

### ISSUE THREAD

**Issue by nameisken** [TortugaPower/BookPlayer#127]
I saw they are no bookmark function be supported. I am wondering, does this because no API(AVFoundation) to support it or any other reasons? in my experience, the bookmark is an essential feature in audiobook players, so does it have any possibility to implement it or any trouble with it?

**Comment by pichfl** [comment]
Thank you for your input! Bookmarks are tricky to get right, but could be very useful for non fiction and reference. If you can help us specify the bookmarks feature in more detail, we would be grateful. 

- Could you elaborate on what you expect from a bookmark feature? 
- How do you expect bookmarks to work? (How do you expect BookPlayer to create, edit, delete bookmarks? Is there a standard for this type of meta data?)
- Is there another app with that feature which works as you expect it to do?

We have #10 on [our Roadmap](https://github.com/GianniCarlo/Audiobook-Player/projects/1) which while rather different seems at least to be related to your request. 

So much for converting your ticket into a feature request, now to answer your question: No, API is not the reason this wasn't implemented yet. BookPlayer is much more than just the rather small part of the actual playback and isn't limited to the API surface of AVFoundation. 

The focus of BookPlayer is to provide an easy to use player for audiobooks. For the upcoming version support for Playlists, faster load times, and a more intuitive and cleaner UI were determined to be the most pressing points to work on. 

As with all feature requests I'm closing this ticket to focus on the work that needs to be done for the current release. It will remain active on our Roadmap and can and should be discussed further.

**Comment by nameisken** [comment]
Thank you pichfl 
I'm using Apple's iBooks and Amazon's Audible application to listen ".m4b" and ".aax" files, they are good but not perfect.

"iBooks" has essential functionality and convenient, snappy UI operations. unfortunately, it doesn't support bookmark feature. 
"Audible" has more functionality and supports bookmark feature, unfortunately, it only supports its own cloud "aax" files, offline "aax" and m4b files will have odd chapter titles and no bookmark functions.

Why I'm so fancy the bookmark feature?
people are used to listening somewhere many times in an audiobook. An audible book same as a textbook which needs marks or underlines to warm up people's memory. this is a big difference for entertainment with music.

Why do I suggest to do it?
Why would people need another audible player when they already have Amazon and apple's player and they are good? this is a question. Except for the essential functions those players should all have(not too much), we should do on the difference which apple and Amazon don't, and the bookmark is the one.

I'm not sure but I would like to do some if I can.
I attached a few snapshots which to specify the bookmarks on Apple&Amazon's players.

![fullsizeoutput_3dd](https://user-images.githubusercontent.com/2951742/40888228-828e605c-6786-11e8-8805-47464dda4063.jpeg)

==============

![fullsizeoutput_3e9](https://user-images.githubusercontent.com/2951742/40888393-158fa0a8-6789-11e8-90d2-ed7984ff3d94.jpeg)

===========

![fullsizeoutput_3d9](https://user-images.githubusercontent.com/2951742/40888151-6402f810-6785-11e8-8e4f-81431fabb88f.jpeg)

========


![fullsizeoutput_3df](https://user-images.githubusercontent.com/2951742/40888227-81d3fb40-6786-11e8-906f-277070649a37.jpeg)

**Comment by pichfl** [comment]
@nameisken I think you'll like the upcoming 3.0 version of BookPlayer. 

Thanks a lot for the input! I'll ignore the part about the chapters and naming because they are not relevant for either the bookmarks nor in the context of BookPlayer as we use the chapter names and title found inside the file.

Looking at the screenshots and testing the Audible app myself I would describe this feature as follows:

- The player has a "Add bookmark" button
    - Saves the play position from the moment the button was pressed
    - Brings up a menu which allows me to add an optional text note to this bookmark, save or remove the bookmark
    - Optionally pauses Playback until either "Save" or "Cancel" was pressed (Audible does not pause and it's very stressful to try come up with a note while the book keeps babbling on) 
- Under "More" there is a list which displays each saved bookmark with the following info:
    - Chapter
    - Position
    - Timestamp when it was saved
    - Text Note 
- Each bookmark has these actions:
   - Edit note
   - Delete note

I do not see the "Share" option in BookPlayer for the first iteration as creating an audio snippet or editing audio in general vastly overshoots the scope of the app. Also I don't want to get into copyright issues. I'm also ignoring the range aspect of the bookmark "clips" with the same rationale.

**Comment by kour1er** [comment]
Just to add my feedback on how I use bookmarks - I think [Bound](http://boundapp.audio) has a really nice implementation of this. In the player section, the user can create a bookmark with one tap (which doesn't create a naming dialogue or anything - just one tap). There is then an additional menu button on the player which lists all created bookmarks for that book with the timestamp listed. 

I find this really useful for when I'm listening to audiobooks falling asleep. I start playback, drop a bookmark, set the sleep timer. Then I can always go back to where I started from in that listening section very easily.

(btw version 3.0 is *so* nice great upgrade)

**Comment by GianniCarlo** [comment]
Thanks for your input @kour1er ! we'll be sure to look how Bound does it too once we get around to implementing this feature 👌 (although we wouldn't mind a helping hand if you want to try this :D )

**Comment by kour1er** [comment]
Of course - always happy to help!

**Comment by GianniCarlo** [comment]
Awesome!

**Comment by GianniCarlo** [comment]
let me know how I can help

**Comment by NightMachinary** [comment]
I suggest you also implement "auto-bookmarks" as the app Bookmobile does. It helps greatly to find one's position when something unexpected happens (e.g., you fall asleep). It would also be great to be able to export these bookmarks to a good format (say json). Syncing them with iCloud would also be nice.

**Comment by GianniCarlo** [comment]
Auto-bookmarks sound good 🤔 by any chance do you know how they might work behind the scenes? iCloud data/profile synchronization is in the pipeline 👌

**Comment by NightMachinary** [comment]
I don’t know, but the basic idea is that any action creates a bookmark,
like skipping ahead, pausing, etc.

**Comment by iamhenry** [comment]
Hi all. I'd like to thank you all for the hard work that is going into this amazing project. 

I wanted to see if there's been an update as to when the bookmark feature will be implemented? 

Thanks again!

**Comment by GianniCarlo** [comment]
Hi @iamhenry , this is currently on hold on my part, since it depends on a redesign (which state can be seen if you run the branch `feature/player-redesign`). Currently on my plate is to take up localization again and finish it this time, then refactor importing files, then finish redesign so bookmarks are supported 👌. If anybody is up to tackle this feature so we can have it earlier, please feel free to let us know so we can give pointers and provide design

**Comment by neotaruntius** [comment]
Hi Gianni... Thanks for keeping us up to date on this feature. Do we have an ETA for when this feature will make it to the app? It's an essential feature for me!

**Comment by GianniCarlo** [comment]
Hi @neotaruntius ! Since last time, I did finish the localization feature, and I'm currently doing the refactor of importing files (it's proving to be a more complex issue than I thought), then we'll continue withthe redesign which includes bookmarks. Giving ETAs is difficult when we can only work on this in our free time, but I hope we can close 2020 with the next major version v4.0.0 which would include the redesign as well

**Comment by neotaruntius** [comment]
Fully understand and again very appreciative of your efforts. Thanks for the quick response @GianniCarlo !!

**Comment by jcqbrc** [comment]
Any update on this? Seems like an essential feature of non fiction books. Thanks!

**Comment by GianniCarlo** [comment]
soonish 😁 we'll be including this in our next major release v4 along some other surprises 💪

**Comment by jcqbrc** [comment]
Oh, very nice. Any sense of a timeline? :)

**Comment by pichfl** [comment]
@jcqbrc it's done when it's done – this is how Open Source works.

**Comment by fivestones** [comment]
> @jcqbrc it's done when it's done – this is how Open Source works.

Everybody know that a timeline given by anyone making software is a best-case-guess at best, and that it typically will require more, or a lot more, time.

It’s still really helpful for impatient people like me to hear a timeline. 😉

**Comment by fivestones** [comment]
I’m not sure how much of this issue may have been completed already but I have a few thought on how it could work assuming most of it hasn’t already been done:

Starting the bookmark at the time the button is pressed would be helpful for some of the things previously mentioned (e.g., keeping track of your spot when you are about to fall asleep). But to replicating the best of what can be done with paper/ebooks, I’d love the option for bookmarks to start a specified amount of time (e.g., 20 seconds) before the button was pressed. This makes them act more like a highlight in a regular book—you read something, realize you really like it or that it was impactful or important in some way, then go back a bit to start you highlight of what you’ve already read. If you start the bookmark at the time of the button press, playing back bookmarks will always take you to the part just after what was interesting. Or else you would have to hear something, rewind a bit, wait until the part of interest is just about to start, and then hit the bookmark button.

There should be an option to set either the back button or the forward button as the bookmark button (or maybe volume up/volume down). That way you can easily bookmark from the Lock Screen or by double tapping AirPods or hitting back/forward on other headphones. If you are inside the app it should be a separate button of its own, so you will also be able to use the normal back/forward functionality from within the app. But this would be huge for bookmarking things while on a run, for example.

Others have said audio manipulation is outside of the scope of this app. But I think two other features are worth mentioning just in case someone thinks they are compelling enough to add anyway. 

One is an option to record my own audio comment immediately after making a bookmark. The workflow might go like this. I’ve selected the option in settings previously. I’m on a run, listening to some great book. I hear something I want to remember, and double tap my AirPods, with my phone still in my pocket. The audio pauses and a chime sounds. I say out loud that the passage I just bookmarked makes me think differently about a particular historical event. I then again double tap the AirPods, and the audiobook resumes. The bookmark created is at a point 20 seconds before I first double tapped the AirPods, so it includes the part of the book I was interested in, instead of the part about to play which I haven’t heard yet.

Finally, there should be a screen in the app where I can see all the bookmarks in all audiobooks in the app, or just for a single book, and from there can listen to my short recording and the bookmark. Being able to in some way highlight or rank and share these would be even  better although I realize that’s a long way off if even doable for this app.

**Comment by GianniCarlo** [comment]
#626 takes care of the initial version and will be released in the next feature version 4.2.0, I'll put up the open beta as soon as possible 🙌

**Comment by tonigarrn** [comment]
Thanks to the team for the great work!

I love this bookmark feature. As a suggestion, I would love the ability to have a start time _and_ an end time for the bookmark (to actually create a snippet). Coupled with the ability to "play all" the snippets at once, to review all the key moments of a given book.

I use this functionality on a podcast app called "Snipd" that completely changed the way I learn from Podcasts. I can easily loop daily through all the snippets of my different podcasts, which helps me better memorize key concepts. It's really a game changer. Currently, the only app I found with similar features is Audible. However, Audible's "clips" (which are snippets) are limited to 45 seconds, which isn't long enough. And they also don't provide the ability to "play all" the clips.

**Comment by fivestones** [comment]
@GianniCarlo @pichfl I second what @tonigarrn says about snippets. I've also been using Snipd lately for podcasts and the ability to just playback all the snippets/bookmarks is amazing.

Snipd also is using ML to create transcripts of the podcasts and more ML to divide up the podcast into sections based on when it thinks there is a new topic starting. When you make a bookmark/snippet, it chooses the whole ML-created section that your bookmark is in for its snippet.

ML on device running locally might be too much at this point for an audiobooks (or maybe not? IDK). But I bet if we had, like @tonigarrn suggested a start and end time for the bookmarks, and the ability to listen to it, we could get most of the benefit of what Snipd is doing.

I'd recommend you try out Snipd for a few days just to see what it can do. A lot of this would be great for audiobooks. Unfortunately they just put most of the ML functionality behind a subscription but I think you can do a free trial.
