### ISSUE TITLE
No way to refresh the list when you add a new book

### ISSUE THREAD

**Issue by GarethBlain** [TortugaPower/BookPlayer#229]
You use to be able to drag down on the play list to refresh the list with new items you've dragged in with iTunes (apart from when there was no files but that might have been a bug in the old one) but the new one (while looking great and I LOVE it so thank you all!!) doesn't have that feature so the only way I have found to refresh the list is to open the iPhones running app screen and force closing the app. When you re-open it after that it will automatically refresh the list picking up the new items.

SO would it be hard to get the pull to refresh back or am I missing how this is meant to work? :)

**Comment by GianniCarlo** [comment]
Hi @GarethBlain thanks for reporting this. For the next minor version (3.1) this [change](https://github.com/TortugaPower/BookPlayer/pull/219) will be included, which will detect and notify the app whenever a file is added via iTunes, thus removing the need of the pull-down-to-refresh. 

I'm glad that you're enjoying the redesign of the app 😄, before considering putting back the pull-down functionality, we'll release v3.1 in September so we can see if it solves that current need. I'll be closing this issue since it's related to #219 . But feel free to continue the conversation 👌

**Comment by GarethBlain** [comment]
Yup that sounds like a perfect solution. 👍
