### ISSUE TITLE
Rewind and fast-track icons are not fully covered by artwork when playing

### ISSUE THREAD

**Issue by Guy27** [TortugaPower/BookPlayer#255]
when the book is paused the rewind and fast forward buttons are visible and are placed each in its relevant position, however when playing the book coverage for some reason is being enlarged and the buttons are getting closer together.
making them only half visible behind the book cover.
it's just not easy on the eyes as it makes it look like a rearrangement bug.
I think it's ok to consider keeping the sizes the same while playing or pausing so UI doesn't change between playing states.
Just a suggestion though :)

**Comment by GianniCarlo** [comment]
Hi @Guy27 , for the redesign we went for something similar to how iBooks handles the rewind and skip forward. Since it's completely different with the interaction we had previous the redesign (v3.0.0), we thought it made sense to leave a 'hint', in the form of a half visible icon and a slight 'nudge' of the artwork.

Regarding the sizes, I'll defer to @pichfl 😄

**Comment by pichfl** [comment]
I suspect your book has a non-square/portrait cover, which might show an alignment error when it comes to the direction icons, which is why I'm labelling this as a bug (and renamed the issue). The UI was meant to go as much out of the way of the listening experience as possible, replacing the need for distinct buttons by tapping (play/pause) and swiping (thumb back/forward). Same goes with resizing the cover, which shows the paused state without looking for a symbol, which, depending on your device, may be a bit excessive and could be toned down a notch.

**Comment by pichfl** [comment]
@ryantstone is that something you might want to help out with? The icons are currently aligned from the outside of a square but they should be aligned from the left and right sides of the artwork so they do not show up for portrait covers when paused and only appear half way when paused.

**Comment by ryantstone** [comment]
Sure. I’m away for the weekend, I’ll take a look some time next week.

**Comment by GianniCarlo** [comment]
Due to #319 , we'll be changing the skip controls into buttons and put them on top of the artwork, so I'm closing this issue since it would no longer apply
