### ISSUE TITLE
Bug Reporting

### ISSUE THREAD

**Issue by ryantstone** [TortugaPower/BookPlayer#264]
Need to assess bug trackers to handle error reporting.
- [InstaBug](https://instabug.com/)
- [Crashalytics](https://firebase.google.com/products/crashlytics/)
- [Rollbar](https://rollbar.com/error-tracking/ios/)
- [BugSnag](https://www.bugsnag.com/platforms/ios-crash-reporting/)

**Comment by ryantstone** [comment]
I have used Rollbar at work for Ruby but not iOS. I've never been thrilled by it but I can't imagine what in a bug tracker would be thrilling. I've used the old version of Crashalytics (crashalytics.com) and the interface was pretty clunky, but I haven't touched the new Google/Firebase version. No experience with any others.

**Comment by pichfl** [comment]
All of the options above will require us to maintain GDPR compliance. Personally, I don't want to touch a service provided by Google given their track record of sunsetting anything that isn't related to advertising. 

We have error tracking via Apples developer analytics which are integrated into Xcode down to the stack trace, but as we haven't got the chance to republish the application under a free foundation yet, those are limited to @GianniCarlo and his account.

**Comment by ryantstone** [comment]
I agree 100% about the Google statement. Instabug has GDPR related features (https://docs.instabug.com/docs/gdpr), Rollbar does not appear to have any GDPR related docs directly addressing the issue and Bugsnag just says it's compliant.

**Comment by GianniCarlo** [comment]
While I'd rather not add more dependencies, I do think we need to eventually move to a third party again, due to:
- (Main reason) There's no notifications of any kind, not for a new crash, not for a regression, not even if it's something critical that's happening to a lot of people.
- (Minor reason) We only get crash reports from people who accepted the option to share these when setting up their device. 

I don't mind the second reason, since if it's a critical bug, it should be happening to most of the devices and it should reach us. But the notifications, is something Apple should have, and it frustrates me a little, since I only remember to open up those crash reports from the Xcode organizer the week before we're planning for a release 😅

**Comment by GianniCarlo** [comment]
InstaBug ruled out, their free tier doesn't provide crash reporting and they don't provide a free alternative for open source projects :/

**Comment by GianniCarlo** [comment]
crashlytics is now part of Firebase, and we're trying to stay away from that. We're left with the last three contenders:
- [] Sentry
- [] Rollbar
- [] Bugsnag

**Comment by GianniCarlo** [comment]
We'll be trying out Sentry for the next few releases and see how it goes
