### ISSUE TITLE
Multi select using DS File (Synology)

### ISSUE THREAD

**Issue by teambatch** [TortugaPower/BookPlayer#293]
When using DS File as the source in Locations you are unable to multi select files for import.

**Comment by GianniCarlo** [comment]
Are you on the latest version of Book player? We enabled the multiple files selection option on UIDocumentPicker some 2-3 versions ago.

If you are on the latest one, I'm afraid that it's a problem of the DS File app, since the file picker that is presented in the app, it's the Apple's component UIDocumentPicker, and it's the responsibility of each File Provider (in this case DS File) to expose the functionality they support.

I'd suggest that you reach out to them or change File provider (iCloud, Dropbox, etc)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by GianniCarlo** [comment]
I'm closing this issue since it's not directly related to BookPlayer. Feel free to continue the discussion

**Comment by pichfl** [comment]
Can confirm, this is a problem with the DS File application. Please consider raising this issue in the [official Synology forums](https://forum.synology.com/enu/viewforum.php?f=215)
