### ISSUE TITLE
Save interaction history as automatic bookmarks

### ISSUE THREAD

**Issue by cuddawudda** [TortugaPower/BookPlayer#299]
I have been a Bookmobile user for a couple of years and there are a few features I would like to see added in Bookplayer. 

This request is for a history of 'bookmarks'. This has occasionally been invaluable when I have left the app playing or inadvertently skipped and I have been able to quickly go back to a previous position. 
What is the best method to share screenshots here?

In the meantime here's a link to a debit on the web. Note that majority are auto created, but some are manually created and text can be edited and colour coded. 

![576x768bb](https://user-images.githubusercontent.com/194641/50797381-e53f2c00-12d4-11e9-8134-56e29f08a37a.jpg)

Edit by @pichfl: inlined image

**Comment by GianniCarlo** [comment]
I need this. Auto-created bookmarks should a huuge help, specially if one falls asleep. I'll revise the [roadmap](https://github.com/TortugaPower/BookPlayer/projects/1) and see where we can add the bookmarks

**Comment by pichfl** [comment]
That is a neat idea! Totally in favor of this.

**Comment by cuddawudda** [comment]
I know i raised this...
But is this a duplicate of  #127 ?

**Comment by GitHubThrowaway31231** [comment]
I've recently started using this app (fantastic work btw!), and I went searching on Google to see if this feature was available which led me to this page.

I just wanted to add that I think this feature would be incredibly valuable, even if it started off as a very simple, non-interactive page which is effectively just an audit of playback actions (e.g. list with entries like "At 10:32am Playback Started at Position 3:32 on Book XYZ").

My use case is that I often listen to books when falling asleep, and so the app will end up being way ahead of where I actually listened to. An audit page would allow me to more easily jump back to a relevant time.

Is this feature likely to be on the horizon at some point? If I had a Mac I'd be tempted to give it a shot myself!

**Comment by GianniCarlo** [comment]
Hi @AeroflotBhutanHymning ! we do plan to bring this feature alongside bookmarks, but it working as an audit page may be out of scope, since there may not be a point in storing past the last 10(?) interactions, and it'll just continue replacing themselves. 

Although we could easily store all, and just present the latest 🤔, and the audit page is an interesting point, for statistics to make them available for the user. We are already storing time spent listening in a day (I explain a bit in #373 ), so it can be queried for a future widget (about how much time one has spent listening to audiobooks), but it doesn't have that depth to distinguish which titles have taken more time. That is something that I'd really like to expand on and be able to show the user a better usage statistic of the app

**Comment by GianniCarlo** [comment]
In the initial version, there are two automatic bookmarks that get overridden `.play` `.skip`, which will record the place before playback is started, or a time jump is triggered by the user (either via the progress slider, rewind or forward button)
