### ISSUE TITLE
Add additional buttons to mini player

### ISSUE THREAD

**Issue by cuddawudda** [TortugaPower/BookPlayer#303]
At the moment this card shows artwork, title, author and play pause button.
Suggest removing title and author and adding skip forward/back buttons. 
Also suggest adding a stronger colored background to distinguish this card from the the library behind. To my eye the colour is almost identical to background.

**Comment by pichfl** [comment]
Removing the labels has more implications for users. Not everyone is sighted. Not everyone uses files which include a cover artwork, not every artwork conveys the full information (especially true for works with multiple parts, series or bigger books split across multiple files).

The current design was chosen to make the cover stand out and make the interactions book-like, similar to thumbing trough pages. I still consider this a valid suggestion and will try to find a solution that fits both current users who enjoy the less crowded screen as well as users like you who prefer to see all controls at once. 

Please elaborate on the background thing. The fact the background and player blends into the colors of the artwork is intentional.

**Comment by GianniCarlo** [comment]
The new design will fix the distinction between the mini player from the library.
Mmmmm if we want to fit in the skip buttons in there, I don't think that removing the labels is the way to go for the reasons @pichfl mentioned

**Comment by cuddawudda** [comment]
> The new design will fix the distinction between the mini player from the library.
> Mmmmm if we want to fit in the skip buttons in there, I don't think that removing the labels is the way to go for the reasons @pichfl mentioned

Hi Gianni, i thing @pichfl and I got our wires crossed initially and I think his response was referring to the  library.

If we consider the mini player. My thoughts (and assumptions!):-
- The listener will know 99% of the time the book and author they are listening to.
- The listeners most frequent actions to perform quickly are pause, play and skip backwards. Possibly also bookmarks function when it is added. Skip forwards is not often needed to be done quickly.
- i think it more useful to more users to have the skip backward function available than the book title and author . Possible also bookmark button.

**Comment by GianniCarlo** [comment]
While I do agree that having the more control buttons in the mini player would be useful, I don't see (in my mind) how to make them fit and still preserve the design style of the app. I'll defer to @pichfl on this.

**Comment by pichfl** [comment]
My updated comment above reflects my position on the mini player. 

The mini player is foremost a quick way to summon the regular player interface. Adding more buttons into a view that is essentially a button in itself would detract from the clean and minimalistic nature of the app.

**Comment by GianniCarlo** [comment]
Alright, with that in mind, I'm closing this issue. I think that for a further discussion on how the app could look in future versions, we could have a more streamlined discussion on design proposals in [BookPlayer's Discord server](https://discord.gg/B5vY2Sh)
