### ISSUE TITLE
Stop at chapter boundaries when skipping

### ISSUE THREAD

**Issue by cuddawudda** [TortugaPower/BookPlayer#305]
As per title , when skipping stop at chapter boundaries. E.g. 7s into chapter 2, rewind 15s goes to the start of chapter 2. 

This will be more relevant if / when longer skips are available

**Comment by pichfl** [comment]
If we do this, this should be an optional setting.

For many books the chapters are rather random and do not match those in the original book because they were made to split up a CD into tracks or something like that.

For books with proper chapters this would be very welcome.

**Comment by GianniCarlo** [comment]
mmmmm not sure about the optional setting. The CD ones shouldn't be a problem, since they end each chapter with 'End of disc <#>', and start the following chapter by repeating the last 1-2 sentences from the previous chapter.
Unless it's a bad rip of a book, so a 'chapter' starts/ends mid-sentence, then it would be detrimental to the experience 🤔. Maybe we could have the setting but with the default being ON

**Comment by pichfl** [comment]
Good point. Works for me.
