### ISSUE TITLE
Problem Importing Files into Playlist from Google Drive

### ISSUE THREAD

**Issue by Yonidass** [TortugaPower/BookPlayer#331]
Recently I've had problems importing files into a new playlist from folders on Google Drive. Sometimes not all of the files import (5 out of 11, for example, in no particular order.) When I try to add the remaining files, the previously selected folder on GD now appears empty, and I can't navigate out of that folder to my main GD. It just appears to get stuck.

These are always multi-file audiobooks, both mp3 and m4a (non-chapterized), with identical file format. When adding files to a playlist, I always navigate to the folder on GD, then choose Select>Select All>Done, then wait for the files to import. When asked, I choose Add to Current Playlist.

Eventually after relaunching the app, playing another audiobook and then trying again, or restarting my phone, it will get unstuck and I can then add the remaining files.

In my BookPlayer library I have about 15 books total, both multi-file audiobooks and single file chapterized m4a/b audiobooks. At first I had no problems creating playlists so maybe my library is getting overloaded. I've tried deleting a few books but it's still happening.

BookPlayer 3.2.1-2 on iOS 12.1.4
iPhone 6s

**Comment by GianniCarlo** [comment]
Hi @Yonidass , unfortunately, once you're inside the file picker, you basically left BookPlayer. So everything happening there is part of the Files.app plugin provided by the app you're using for file storage, which in this case is Google Drive.

We would love to provide a direct integration to multiple cloud services, but due to lack of man-power, we'll have to keep relying on this native component provided by iOS for the foreseeable future. 

Once we start the phase with iCloud integration, we can take a look at this issue again.

I'm closing this issue as it is sadly out of BookPlayer's control.
