### ISSUE TITLE
Siri "continue my book" requires unlock

### ISSUE THREAD

**Issue by emkayonline** [TortugaPower/BookPlayer#338]
When using a Siri shortcut to "continue my book" (using my AirPods) I am prompted to unlock my iPhone. 

Apps such as overcast do not require the unlock to start playing.

Is it possible to support "continue my book" without requiring unlock (this would also help in the car when I use "Hey Siri".)

Using v 3.3.0 of BookPlayer on iOS 12.1

**Comment by GianniCarlo** [comment]
thanks for letting us know @emkayonline , we'll be releasing a bug fix release 3.3.1 next week, and we'll include this among the fixes

**Comment by GianniCarlo** [comment]
after doing a deep dive into this, I'm sad to say that we will have to postpone this issue due to the way we implemented Siri shortcuts.

To implement Siri shortcuts there are two routes, the easy one and the long one. We did it the easy/fastest way, which was to use an object from the class `NSUserActivity` and creating an `INShortcut` based on it.
The longer, proper way, is to create an app extension and create a custom intent for Siri.

The problem with this last approach, is that to properly create an app extension, I have to bring back part of the work I did for the watch app branch, which unified commonly used libraries to access the app data into a single shared framework, from which all the app extensions can benefit.

This will happen eventually, since it's in the plans to have both a watch app extension and a widget app extension, but until that happens, we can't create a proper Intents extension, which opens up more properties of the shortcuts that can be modified (see the following picture)

<img width="585" alt="Screen Shot 2019-04-01 at 8 23 42 PM" src="https://user-images.githubusercontent.com/14112819/55369768-86e1ae00-54bd-11e9-919b-af88ea35c70c.png">

**Comment by GianniCarlo** [comment]
for reference:

- [INShortcut class reference](https://developer.apple.com/documentation/sirikit/inshortcut)
- [INIntent](https://developer.apple.com/documentation/sirikit/inintent)
- [NSUseractivity](https://developer.apple.com/documentation/foundation/nsuseractivity)

Which don't include a property to modify the authentication requirement. Any input on this from someone who has gone through this before would be welcomed.

For the time being, doing the `Intents` app extension would be the solution to this

**Comment by crozo5** [comment]
Is a short-term solution planned?

**Comment by GianniCarlo** [comment]
I think we can solve this now, for 3.8.0 we implemented a custom Intent for the sleep timer shortcut, and I'll write my findings here.

With the custom intents (or the intent definition file), we can bring background support to avoid requiring the user to unlock the phone, there's only one problem when it's a custom one, there's no direct communication with the main app, and while we have separated the things into a shared framework so we could have a working watch app companion, we haven't include a way to queue things for the player, since the watch extension has a direct way to communicate with the main app.

There's an alternative though, for system shortcuts (which the last-played shortcut could transform to be), those have an option not available to custom shortcuts, which is to handle the thing in the main app, and the intent is passed to the AppDelegate.

So while the Sleep Timer will not have background execution support yet, we can change the existing last-played shortcut to a system-type, and benefit from the extra options it brings

**Comment by GianniCarlo** [comment]
#449 fixes this with the introduction of a new shortcut 👌

**Comment by crozo5** [comment]
> #449 fixes this with the introduction of a new shortcut 👌

Is an app update necessary? I don't see any new shortcut in the app and the old shortcut keeps asking me to unlock the screen.

Thanks

**Comment by GianniCarlo** [comment]
@crozo5 we haven't released a new version yet, but we'll soon have it available in the appstore 👌
