### ISSUE TITLE
Feature request: Audio Equalizer for player

### ISSUE THREAD

**Issue by northernSky** [TortugaPower/BookPlayer#385]
Hi,
Currently, we cannot do any change in audio sound.
It would be nice if we could do some modification on sound, such as truncate silent or low-pass filter.
I usually use Audacity to truncate silent (silent sound is < -10db and silent time >0.5s). This help me shorten the book about 25% without the need to change tempo (speed).
For low-pass filter, it could reduce stress for our ears if we listen for long time. Some audiobook are record or compressed in poor way, and cause some sibilants in audio. I usually filter the sound > 5000hz out of my audio.
If bookPlayer supports these feature, I don't need to do any pre-processing the audiobook anymore.
Currently, I'm using version 3.5.1-4 on ios 13
Thanks for reading this :D

**Comment by pichfl** [comment]
Thanks for bringing up these two very interesting feature requests. 

#### Audio Processing (Filtering)

While I mostly agree with your thoughts on processing non-ideal voice recordings, doing these steps lies beyond the current feature-set and capabilities of BookPlayer. 

Doing these effects live requires processing power and makes it impossible to rely on the system audio player and would require us to switch to a custom one which adds additional complexity. Doing them in an additional step would require additional UI as it must be an optional process since people might have pristine files that do not need any processing.

#### "Smart speed" (Pause reduction)

Same as with filtering, reducing pauses requires us to switch to a custom audio player and to do some processing before file can be played. I'm a big fan of this and the thresholds you describe seem sensible, but doing this is not something we will be able to support right now. The processing is a complex task and since this is a hobby project we need to make sure not to introduce more complexity than we can handle. 

If you or someone else wants to implement this and provide a pull-request, please contact us either here or via email so we can discuss necessary UI and integration. 

As this will not be on our personal roadmap for the foreseeable future, I'm closing this issue.
