### ISSUE TITLE
Bind playlists into books with chapters

### ISSUE THREAD

**Issue by pichfl** [TortugaPower/BookPlayer#389]
Playlists are a versatile feature of BookPlayer. They allow users to sort anthologies and other multi-part series into a convenient place. They also allow people to easily wrap books that consist of multiple small files so they can be handled more easily. We also allow archives of these small files to be imported as playlists directly. 

While playlists work rather well for the first use-case, they tend to be rather brittle and prone to problems for the second one (see #348, #381, #350, #349 #354, #311 and probably others)

@GianniCarlo found a rather appropriate name for the missing feature here. The ability to "bind" playlists into books, thus allowing us to treat a playlist of multiple files like it was a single book item with Chapters. 

- binding a book would be a non-destructive action and can be undone
- bound books re-use meta-data from files (artwork, author,)
- bound books can be part of a playlist

Binding should be a single action "Bind into book" (with an appropriate icon) at the very end of the playlist, after the import action. I considered adding it to the top, but the right most space in the navigation bar is reserved for the edit button and it's not a proper edit action of the list either. 

The title of the book shall be derived from the playlist name. The author from the first file which includes IDE3 information (fallback: "Unknown"), same goes for the album artwork (no fallback). The chapter names should match the titles and fall back to file names (without the extension). 

Binding a playlist should remove the playlist from the Library, it being replaced by the bound Book.

A bound book looks and behaves just like any other single Book item with few exceptions:

- if possible, it should be exported as an archive
- it has an additional menu item in the "more" menu, which allows you to "Unbind" the book into a playlist with the same name

**Comment by devil418** [comment]
I would also suggest the ability to bind directly in the "add to playlist / add to library" prompt, i.e. when importing from a zip file. An option called "import as book" would probably be appropriate.

**Comment by pichfl** [comment]
While answering #428 I noticed I haven't provided a strategy for handling book parts which have chapters themselves. 

I propose to keep the chapters from individual parts and adding the title of the part as additional meta data in some way.

eg. for 
| File | Chapters |
| ---- | ---- |
| Lord of the Rings - The Fellowship of the Ring - Part 1.mb4 | Foreword, Prologue |
| Lord of the Rings - The Fellowship of the Ring - Part 2.mb4 | Chapters 1 to 12 |
| Lord of the Rings - The Fellowship of the Ring - Part 1.mb4 | Chapters 2 to 20 |

We could bind `Lord of the Rings - The Fellowship of the Ring`
and have a list 
- Foreword<br><small>From: Part 1 – Start: 00:00 – Duration: 03:00</small>
- Prologue <br><small>From: Part 1 – Start: 00:00 – Duration: 04:00</small>
- Chapter 1 <br><small>From: Part 2 – Start: 00:00 – Duration: 12:18</small>

and so on. The `Part 1` must not be merged into the chapter title, so it can be displayed in the secondary label of the chapter list (in front of the chapter start time and duration)

**Comment by JoshuaCrewe** [comment]
This sounds like something I would find really valuable I think. I haven’t been using the app long and I am getting a feel for how it all works.

I wanted to sense check the current behaviour against this feature.

I have a couple of audiobooks I got from my local library. They are all mp3s and come with all the metadata filled in. When using iTunes they are considered one book. Same with iBooks too.

When importing them to this app each file is it’s own “thing” in the library and needs to be put in a playlist. Then there isn’t really a connection between the files other than they are in the playlist. The progress percentage is relative to the file rather than the playlist when playing and the chapters list is greyed out. 

While this makes sense on one level I would have expected the same behaviour that iBooks displays. So the question that is relevant to this issue is, am I doing it wrong? Is this the feature which addresses my scenario?

Reading this makes me sound entitled so I want to say, great work on the app and I love the welcome messaging about contributing 🥰

**Comment by pichfl** [comment]
@JoshuaCrewe would you mind joining us [on Discord](https://discord.gg/MjCUXgU)? I haven't come across the behavior you describe in iBooks, so I would love to inspect some of those files. 

The "binding" would bring the behavior you expect, even more so if we can use the same mechanism iBooks applies.

**Comment by JoshuaCrewe** [comment]
Ok great! Lets chat on Discord, I made an account there.

**Comment by pichfl** [comment]
For future reference: The apps mentioned by @JoshuaCrewe use the Album title IDE3 reference to associate the files. We should do the same when filled and possible 🙂

**Comment by GianniCarlo** [comment]
This will be included in the next release 🎉
