### ISSUE TITLE
Option to allow autoplay to include completed

### ISSUE THREAD

**Issue by 0x6C77** [TortugaPower/BookPlayer#391]
Re-listening to audiobooks made of multiple files is frustrating as the autoplay option doesn't play items that have been finished.

Adding an option to include finished files in autoplay would remove the need to go back through each file and marking them as unfinished each time.

**Comment by pichfl** [comment]
Thanks for bringing this up. 

While it is somewhat related to #381, I think you might have come across an actual bug here. 

If I remember correctly, @GianniCarlo and I had a discussion about the very scenario you describe and decided to play files regardless of completion state which would be the opposite from what you're experiencing.

**Comment by pichfl** [comment]
In the mean time: You should be able to reset the play state for a playlist by using "Jump to start" from the playlists "More" menu that is available when swiping left. We are aware of the confusing labeling, see #349

**Comment by GianniCarlo** [comment]
I'm happy to report that this was fixed I believe either in one of the 3.7.x iterations 🙂. Thanks for reporting this @0x6C77
