### ISSUE TITLE
iOS share sheet support

### ISSUE THREAD

**Issue by GianniCarlo** [TortugaPower/BookPlayer#401]
When the user is sharing audio files from other apps, among the options in the share sheet, it'd be nice if BookPlayer is among the apps. This would cover more use cases for importing files into the app

**Comment by Resonanz** [comment]
I an trying to import from OneDrive and I cannot believe how close to impossible it is to do. OneDrive does not make it obvious whether the file is "Offline" or not, so the importing thing (I think) gets confused and just takes forever. If I try to import the same file (228 MB zip file containing MP3s) from the iPhone storage (not sure where exactly that resides on the phone itself) rather than from OneDrive then it imports immediately. 

All that said, importing is such a fundamental part of apps like this, and this morning has been a very frustrating experience for me, just trying to get a single zip file into BookPlayer. 

I think I am a good critic of UI design, so would be happy to help out in this area as required.

**Comment by pichfl** [comment]
As stated in #412, we are not in control of the UI provided by various file providers for iOS. To send feedback for OneDrive, use [their suggestion platform](https://onedrive.uservoice.com), to be honest, they could use your critique. 

To keep the conversation focussed, let's continue in #412, this issue discusses the necessary implementation of a share sheet extension to improve the way out of a third party app into BookPlayer.

**Comment by pichfl** [comment]
BookPlayer already shows in the iOS share sheet, it might just be buried into the "More" section of the iOS 13 share sheet.
