### ISSUE TITLE
Sorting

### ISSUE THREAD

**Issue by Resonanz** [TortugaPower/BookPlayer#423]
*Feature*

I just imported an audiobook onto my wife's iPhone. The chapters were titled:

Chapter One
Chapter Two
...
Chapter 25

* What is the current behavior?
The first thing she asked me was why the ordering was wrong,.e.g. NOT in the order above. I suggested sorting by name in alphabetical order. That gave the wrong order. Sort by original file name did work, but neither of us have any idea what that actually means, e.g. it is confusing to us stopped end users.

* What is the expected behavior?
First, the option to sort is not easy to find. Second, the wording is confusing -- "original file name". Third, the ordering should know that "One" comes before "Two" and "Two" comes before "Three", which means testing not just for "1", "2", "3" etc. but also for the words.

* What is the motivation / use case for changing the behavior?
To improve the app performance to prepare for world domination.

* Please tell us about your environment:
    * Version of BookPlayer = latest version
    * Your Device and its OS version = iPhone 6

Thanks for all the efforts -- we generally love your app !!!

**Comment by pichfl** [comment]
We can't support natural language processing for chapter names, as they could be in any possible language and books themselves might contain numbers which means this would never deliver reliable results. I can count in German and English and probably in Italian, Spanish, Latin and French, but I'm lost for Russian, Chinese, Japanese, Polish and the vast number of other languages on our planet, not counting for misspellings of numbers or worse.

Having said that, we should sort by original file name in the first place and use natural sorting (looking at numbers in the filename first before sorting alphabetically). 

To clarify further, the original file name is the name of the file you imported into BookPlayer. We generally try to display nice names based on the IDE3 metadata of the file (which is what gives you "Chapter One" instead of chapter_01.mp3)

**Comment by GianniCarlo** [comment]
All imported files should be sorted by original file name 👍 by default
