### ISSUE TITLE
Does BookPlayer support ReplayGain?

### ISSUE THREAD

**Issue by rayshan** [TortugaPower/BookPlayer#435]
Specifically the ones processed with this app: https://projects.sappharad.com/mp3gain/

Thank you for all your work on this wonderful app!

**Comment by GianniCarlo** [comment]
Hi @rayshan , from the link you provided:

>What does MP3Gain Express do?
This version of MP3Gain does three things. It can:
Analyze MP3 files and write the volume information to a tag without changing the audio data itself. This is useful if you have a player that supports "ReplayGain" tags. (Not iTunes or iPods, so mostly useless on Mac OS X)

Since ReplayGain don't actually re-encode the audio file, and only writes the information into a custom tag in the file, I can say right from the start, that we don't support ReplayGain tags.

We could look into providing support for it, but sadly I don't see a section where they specify how to adopt it

**Comment by rayshan** [comment]
Thank you @GianniCarlo, I can re-encode, so it's not a must-have for me. It may still be helpful for others though. Feel free to close the ticket.

**Comment by GianniCarlo** [comment]
👌 let us know if you have further questions
