### ISSUE TITLE
New shortcut sleep timer

### ISSUE THREAD

**Issue by crozo5** [TortugaPower/BookPlayer#450]
The shortcut "Sleep timer" doesn't work when I select "Sleep at the end of current chapter" in the options.

And when I select the seconds option in the shortcut, the countdown starts even if the audiobook is paused.  Although that's a minor problem.

**Comment by GianniCarlo** [comment]
Hi @crozo5 , are you on the latest version 3.8.0 (that was just released to the appstore today)? on the last beta from yesterday, we fixed the lack of feedback for that option. You should now see next to the moon icon the word `On` if you're running BookPlayer in English.

We currently don't show the seconds remaining in that option, due to how it works. It sets a listener for the events of when a chapter or book finishes, and then the sleep timer is triggered and pauses the playback.

Let us know if this covers your case, otherwise, I would ask you to verify if doing it manually from inside the app makes the `On` label show up and let us know

ps. Since Apple's review time was like 3-4 days last month, we hoped that the last beta version would be available more time before it went live.

**Comment by crozo5** [comment]
I have the latest version of the App store (3.8.0).  If I activate the sleep timer option "End of current chapter" manually from the App, the word On appears next to the moon.  The problem is when I activate it through the new shortcut, if I activate the "Sleep at the end of current chapter" option from the shortcut, a -2 appears next to the moon and after 2 seconds more or less it disappears.

**Comment by GianniCarlo** [comment]
Oh damn, yeah I just saw it, thanks for the heads-up. I'll update the app with a fix

**Comment by GianniCarlo** [comment]
#451 solved this, and it will be included in 3.8.1, which should be available as soon as Apple approves it

**Comment by crozo5** [comment]
Is it possible to make the sleep timer shortcut run without unlocking the iphone?

Thanks

**Comment by GianniCarlo** [comment]
@crozo5 hi!, unfortunately not at the moment, for system shortcuts like the new resume book that we introduced in 3.8.0 (I think), it's possible since we can send the event to the main app on background, and it will handle it with no problems, but for fully custom shortcuts, that option is not available, instead it's handled by the shortcut-app-extension, which due to it not being able to directly communicate with the main app, we can't send the signal.

I think that to make it available, a big restructure should be made, so the Player class can be shared between the main app and its extensions, and there could be some sort of queuing system, but it's too big of a change for little gain. I'd rather wait for the iOS 14, they may expose those private apis to the custom shortcuts and we can skip reworking the whole app
