### ISSUE TITLE
Audio cuts-out ~3:20-3:40 into a >30 min mp3

### ISSUE THREAD

**Issue by steve0086** [TortugaPower/BookPlayer#466]
* Do you want to request a *feature* or report a *bug*?
* What is the current behavior?

BUG Audio cuts-out ~3:20-3:40 into a >30 min mp3. It seems all tracks in 2 of my audio books cuts out roughly 3:30 into the track. The player continues, but there is no sound - playing the track in any other player works.
iPhone 11+
54 Tracks imported from iCloud as a playlist
Alternatively I tried a 12 hour mp3 track From iCloud and it was Fine ... it really seems to be specific to these 2 audio books so far

* If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo / screenshot / screen recording of the problem. 
* What is the expected behavior?
* What is the motivation / use case for changing the behavior?
* Please tell us about your environment:
    * Version of BookPlayer
    * Your Device and its OS version
* Other information

**Comment by pichfl** [comment]
Given it doesn't happen when using a different file and I'm unable to replicate this with any of the various testing files, there is most likely something wrong with that MP3. 

It may work fine in other players, but the playback engine we use (because it is integrated in iOS and therefore low on energy consumption while still offering everything we need) may be a bit finicky when it comes to files with slight errors. 

Can you try running your MP3 through [MP3val](http://mp3val.sourceforge.net), which is a free tool to validate MP3 files?

**Comment by GianniCarlo** [comment]
Echoing what @pichfl said, it's been consistent that when this was reported via mail support. After doing the validation with ffprobe of the files, and the user running ffmpeg or another converter for the file, then the duration header gets fixed, and the issue goes away

**Comment by Scross086** [comment]
Hi @pichfl , 
Thanks for the feedback - I tried running it through MP3Val and there were no errors detected. It's strange that tracks on books from this particular series seem not to work in the app. Playing them individually on the iphone, they work ok. 
I will try @GianniCarlo 's suggestion and convert the files again to see if that works once I get time towards the weekend. 
Thanks again.

**Comment by pichfl** [comment]
@Scross086 any chance you found out more? I'll reopen the issue then.
