### ISSUE TITLE
Inbox folder

### ISSUE THREAD

**Issue by rastaman111** [TortugaPower/BookPlayer#502]
Good afternoon!  
I have 2 questions: 
1. How do you track the movement of files from iTunes or airdrop 
2. How did you bypass the creation of the indox folder and immediately move the file to the main directory, it is best to say in which file it is re-edited, very interesting, for your application

**Comment by GianniCarlo** [comment]
Hi @rastaman111 !

1.- If I remember correctly, Airdrop files arrive at the Inbox folder, we do have a watcher that gets notified when a new file is added, and it has a waiting threshold to see if there's additional content before firing off a new import operation. iTunes work in kind of the same way, only that they're put into the root of the Document folder (which contains the Inbox folder as well)

2.- We currently move all the files into a 'Processed' folder, so anything outside of it, it's currently 'not' in the digital library. This lets us ignore the Inbox folder, but we've already hit the shortcomings of this approach, and are working on changing the whole way we handle file imports

For starters, we plan on keeping the same file structure on disk as it's presented in the digital library, so the app can play nice with Webdav and other technologies that may access the folder structure so the user can better navigate the library. This will also mean that we'll no longer restrict to playlists of one level, at this point they could be referred to as folders, since there could be folders inside folders.

Let me know if you'd like to know more about the process 👍

**Comment by rastaman111** [comment]
@GianniCarlo Now I'm interested in how you implemented a listener for adding a file from outside.  Could you tell me which file of your application implements this?

**Comment by GianniCarlo** [comment]
sure!, I made it into a separate library: https://github.com/GianniCarlo/DirectoryWatcher , I based that implementation in large part from one made in Obj-c, and I took inspiration from another library which kind of goes into the same subject. I'm planning on making that available via the Swift Package Manager, since we'll soon transition this project to use the SPM as the dependency manager (Carthage giving problems in Xcode 12)

**Comment by rastaman111** [comment]
As I understand it, in order to avoid the appearance of the inbox folder, you created a folder in the main directory, and store everything in it.  But as you said, it was not the best solution.  And according to your library, I saw it, but when I looked at your project, I did not find where you use it to track the movement of a new file from outside

**Comment by GianniCarlo** [comment]
In the `AppDelegate` you'll find the `import DirectoryWatcher` statement, and down in the file, the function `setupDocumentListener`, it then passes the event to the `DataManager` class, which has a instance of the `ImportManager` class, who handles the waiting for new events before firing the import event with a `ImportOperation` of the new urls that were reported

The library viewcontroller handles listening to these events, and then call the `DataManager` to queue these `ImportOperation` which are subclasses of the native `Operation` class, which can be queued into `OperationQueue` and it gets processed in due time.

Since an import operation can be a heavy process, and it could actually happen that the user starts importing new books midway the first import operation, we went with the `Operation` and `OperationQueue` approach to handle the things in the background

The class `ImportOperation` in the `main` function actually has the logic to 'process' the file import into the digital library, at some point after this, the CoreData object is created from these 'processed files', there's a callback for the completion of each `ImportOperation` (search for the function `handleOperationCompletion`)

**Comment by rastaman111** [comment]
Hello @GianniCarlo !  I studied your code and implemented it into my project, a new goal, this is how you display the LoadingView, what is responsible for what?

**Comment by GianniCarlo** [comment]
That's easier, based on when the import is going to start, a notification is fired off, the library is listening to these events so it can show the loading view.

I'm closing this issue, but feel free to join us on Discord (link in the readme) to further talk about the project

**Comment by rastaman111** [comment]
Hello @GianniCarlo , why when moving a file from Inbox to the main directory, the file is not renamed to its original name, but remains as an encoded name via IDZSwiftCommonCrypto
