### ISSUE TITLE
ImportOperation

### ISSUE THREAD

**Issue by rastaman111** [TortugaPower/BookPlayer#510]
Hello again!
Such a question, I downloaded audio in safari, I want to send it to my application, then it does not perform an action where is the breakpoint, the debug writes that the attribute is nil
Although the above application accepts the same file calmly
What could be the mistake?

Thanks

<img width="1096" alt="Снимок экрана 2020-11-02 в 18 05 57" src="https://user-images.githubusercontent.com/15727518/97883535-0688cc00-1d36-11eb-9b8a-2293f6ca6116.png">

**Comment by GianniCarlo** [comment]
@rastaman111 we've revamped how importing works right now, we no longer need to read the whole file to get an identifications, I would recommend to test again in v4.0.0 and see if it works with that. Please feel free to [join us in Discord](https://discord.gg/MjCUXgU) 👍

**Comment by rastaman111** [comment]
> @rastaman111 we've revamped how importing works right now, we no longer need to read the whole file to get an identifications, I would recommend to test again in v4.0.0 and see if it works with that. Please feel free to [join us in Discord](https://discord.gg/MjCUXgU) 👍 

Hey!  I learned a new import method and found it interesting.  But it would be interesting if when the zip file was unzipped, and not 2 times a screen with files opens

**Comment by GianniCarlo** [comment]
@rastaman111 yeah I get what you mean, and that would be a good improvement on the current way import works. We would need to make the `ImportOperation` an async operation (see reference: https://www.avanderlee.com/swift/asynchronous-operations/), so that the unzipping files can be handled/processed and the resulting files appended to the final `processedFiles` array
