### ISSUE TITLE
Sleep timer preset

### ISSUE THREAD

**Issue by DoroLala** [TortugaPower/BookPlayer#511]
You would be my heroes if you could include a possibility to preset the sleep timer once and for all, so i.e. each time I start my audiobook, it automatically stops after 30 minutes without any further action required, so that I don’t need to restart the sleep timer each time- that would be just great!

**Comment by GianniCarlo** [comment]
Hmmmm I think this is better achieved via a shortcuts 🤔 , though not perfect (since via shortcut it's only possible to resume the last played book) but it's an option.

The shortcut route can be done in two ways, one having the shortcut as an icon in your homescreen, the other one triggering via siri voice commands (in this case, name the shortcut with something distinct for siri).

The shortcut would have the following:

![IMG_7287](https://user-images.githubusercontent.com/14112819/99342650-5e592400-285a-11eb-8238-7163f39944c8.PNG)

**Comment by mlosev** [comment]
Unfortunately, such shortcut doesn't work properly when launched from Apple Watch.
While the first action (Resume last played book) succeeds, the second action (Set sleep timer) fails with not a very helpful message:
![IMG_0032](https://user-images.githubusercontent.com/7642914/106360444-57e23080-6310-11eb-915e-7c9a24877468.png)

**Comment by GianniCarlo** [comment]
Hmmmm true I tried it out (I wasn't aware that you could run shortcuts directly from), that's a bug, I'll look into it

**Comment by GianniCarlo** [comment]
ok, so here is what I tried and what I found out:
- Debugging the app and running the shortcut from the watch, the app only gets notified of the first part of the shortcut (the one about resuming playback), the second part fails on the siri shortcut watch app, and the main app never gets the callback
- Running the shortcut from the phone, it all works out (via voice command as well)

Not sure why it's failing, since we don't get any info in the app, but it looks like this is a common issue when doing things from the Watch in the latest versions, this is a thread I found about issues way back from 2018 with the Home app https://discussions.apple.com/thread/8656925

**Comment by OSchu78** [comment]
Hi, i have a similar request too...
Maybe it is possible to etablish an opt in option to make the sleep timer settings globally since i disable this option. So i can choose to set the sleeptimer for current book only or for all books in the library.
That would be great!

**Comment by elric667** [comment]
Wondering if we could just have an automatic sleep timer setting that allows us to reset the sleep timer by shaking it.  Also, be able to set sleep time volume decrease over time allowing for volume decrease over up to 1 minute.

**Comment by OSchu78** [comment]
Shaking the device works only within the time range selected, but when the time is expired the sleep timer will be disabled until you arm it manually again.
So if i can set the sleep timer globally and it expired once and i start the book again, the timer will be armed automatically again about the period i've setting the last time.
If i am listening to a book with several chapters of approx. 20 minutes length each and i've set the time to "end of chapter" i can rearm the timer for the next chapter by simply pressing play again on the earphone remote without touching the phone for setting the sleep timer again.
So when i am setting the sleep timer it will be active until i disable it. That's what i'm looking for.
Thanks in advance!

**Comment by elric667** [comment]
> 
> 
> Shaking the device works only within the time range selected, but when the time is expired the sleep timer will be disabled until you arm it manually again.
> So if i can set the sleep timer globally and it expired once and i start the book again, the timer will be armed automatically again about the period i've setting the last time.
> If i am listening to a book with several chapters of approx. 20 minutes length each and i've set the time to "end of chapter" i can rearm the timer for the next chapter by simply pressing play again on the earphone remote without touching the phone for setting the sleep timer again.
> So when i am setting the sleep timer it will be active until i disable it. That's what i'm looking for.
> Thanks in advance!

I completely agree I want these features for the Bookplayer it is the only thing I miss going from Android to Iphone is that I lost my Smart Audiobook.

**Comment by GianniCarlo** [comment]
This is now live on the AppStore in v5.2.0, Settings → Player Controls → Auto  Sleep Timer, it will restart the last active sleep timer when resuming playback
