### ISSUE TITLE
Bug: The Size on iPad

### ISSUE THREAD

**Issue by Mrtz11** [TortugaPower/BookPlayer#517]
Please adapt the app for the iPad. Otherwise it is only displayed in very small or enlarged and blurred form. It's really not nice. Otherwise the app is very good, thank you very much

**Comment by pichfl** [comment]
Thanks for your interest, but this is not a bug.

A dedicated version for the iPad is planned since #230, but don't hold your breath. Unless someone steps in and helps us to overhaul the UI, this will have low priority over better sync, a new file system and internal restructuring to make an iPad version even possible.

**Comment by Mrtz11** [comment]
Thanks for the answer. I'm a student and all of my audio lessons are on the app. I always learn with it and the app is almost perfect. There is no other app that comes close in terms of level. And luckily it's even free, unfortunately i can't afford an app that costs something. Thank you very much for this great app. As a student I use an ipad and of course it would be very good if it were adjusted correctly. I support you by recommending your app to everyone. Thank you. I would be very happy if it doesn't take too long until it works for the iPad. I wish you success
