### ISSUE TITLE
Bug: Privacy Policy Missing

### ISSUE THREAD

**Issue by chrisjf** [TortugaPower/BookPlayer#522]
# 💬 Description

I clicked (Nov. 28, 2020) on the Privacy Policy link in the App Store and was forwarded to the project's GitHub Page. Where is the Privacy Policy for this app? Could it be put in the repository? Could the App Store link be updated? Thanks.

**Comment by pichfl** [comment]
@chrisjf thanks for bringing this up! We had a website before but it is defunct by now and given we redirect here, we should put the policy straight into the repository.

The privacy policy was very short anyway.

> Right now we do not track our users beyond the optional Apple Developer Statistics which you can enable or disable either when setting up a new device or in the Settings.app of your device.

However, I'm glad you asked, because future versions will use https://apptelemetry.io to help us gain some anonymous insight on how people are using BookPlayer so we can decide on what to prioritize. That service is completely anonymous and in line with Apples strict Guidelines.

**Comment by chrisjf** [comment]
Thank you for the reply with the (very short!) privacy policy. 

# Action Items:
- [ ] Put the privacy policy in the repository
- [ ] Update the link in App Store

**Comment by GianniCarlo** [comment]
we've added our [Privacy Policy](https://github.com/TortugaPower/BookPlayer/blob/main/PRIVACY_POLICY.md) and updated the App Store page as well 👍, thanks for bringing this up @chrisjf
