### ISSUE TITLE
Bug: screen stays awake during playback

### ISSUE THREAD

**Issue by baron** [TortugaPower/BookPlayer#541]
# 🌎 Environment

 - OS Version: 14.3
 - Version/Release: 3.11.0-2

# 💬 Description

During playback the lock screen is prevented from going to sleep. I would rather it obeyed the screen sleep settings and went dark after the time lapse of the settings or stayed dark until awakened.

# 🦶 Reproduction Steps

Steps to reproduce the behavior, provide an example of the command line issued:
1. Play book
2. lock screen (press power button)
3. press homebutton
4. lock screen stays awakened indefinitely

# 🤔 Expected Results

# 😲 Actual Results

A clear and concise description of what actually happened.

# 🤝 Relationships

- Related PRs or Issues: #xxx, #yyy

**Comment by pichfl** [comment]
Have you checked the BookPlayer settings? We do have an option there which explicitly prevents the screen from locking. 
Once you leave BookPlayer, the screen is no longer in our control.

**Comment by GianniCarlo** [comment]
Yeah the lock screen is out of our control, we can only provide the metadata for the now-playing view there via Apple's API, nothing else. Echoing what @pichfl , the only control we have is inside the app, and in that regard, we can only prevent the phone from _locking_ automatically.

I'm closing this issue, since from the info provided, nothing can be done from within BookPlayer. Side-note, in my day to day, when I'm charging the phone (connected to my laptop), the screen does tend to stay lit until I manually turn it off, not sure if it's something with iOS. Feel free to continue the discussion 👍

**Comment by baron** [comment]
> I'm closing this issue, since from the info provided, nothing can be done from within BookPlayer. Side-note, in my day to day, when I'm charging the phone (connected to my laptop), the screen does tend to stay lit until I manually turn it off, not sure if it's something with iOS. Feel free to continue the discussion 👍

Yes that’s the exact issue I’m talking about. I guess it must be an iOS but then. Thank you!
