### ISSUE TITLE
Ability to Import M4B files

### ISSUE THREAD

**Issue by caughtadeer** [TortugaPower/BookPlayer#575]
Would love to be able to import m4b files. Thanks guys.

**Comment by red-ochre** [comment]
I do that now from macOS. Connect iPhone to Mac with either USB or WiFi. In Finder open the phone’s folder then the Files tab. Then drag ‘n’ drop the m4b to the BookPlayer folder. The BookPlayer app on the phone will import the book.

Cheers,

**Comment by pichfl** [comment]
Importing `m4b` files is a basic function of BookPlayer from the very beginning of the app. You can send them via AirDrop on macOS or another iOS device or via the method @red-ochre describes or from any cloud service connected to Files.app on your device. We even recommend M4B as the default format for your audiobooks as it makes handling much easier.

If you have an issue importing a specific file, please contact support@bookplayer.app with details.

**Comment by jasonblewis** [comment]
I think OP might have been referring to the inabliltu to select m4b when importing in app. Steps to reproduce:

Touch add/import files, then select a folder that contains m4b files. Note they cannot be selected. See screenshot

![467EC415-6AE2-4159-803D-C79F09A1ED6D](https://user-images.githubusercontent.com/129165/113788978-93bacb80-9781-11eb-863a-c363616a0572.png)

**Comment by GianniCarlo** [comment]
Hi @jasonblewis I recently responded via email as well, this is the line I'm referring to that we present the document picker Apple provides for us

https://github.com/TortugaPower/BookPlayer/blob/92b2d62a6806153af3e9b34683c05f5cdff7235d/BookPlayer/Library/ItemListViewController.swift#L194-L195

we pass `public.audio` which according to [Apple's reference](https://developer.apple.com/library/archive/documentation/Miscellaneous/Reference/UTIRef/Articles/System-DeclaredUniformTypeIdentifiers.html#//apple_ref/doc/uid/TP40009259-SW1) should contain mp3, m4a and m4b (along with other audio formats), which is why it looks like the problem lies in the cloud-provider implementation of their integration, since for example with iCloud there are no problems (we've heard reports of problems with Google Drive if I remember correctly)

**Comment by jasonblewis** [comment]
@GianniCarlo thank you for your detailed response and diagnosis. For what it's worth in this case it is the ownCloud client. I will see if i can report the issue to them
