### ISSUE TITLE
Bug: Error when umlaut in filename

### ISSUE THREAD

**Issue by homeuser99** [TortugaPower/BookPlayer#576]
# 🌎 Environment

 - OS Version: [e.g. 13.5.1]
 - Version/Release: [e.g. 3.9.0-1]

# 💬 Description

# 🦶 Reproduction Steps

Trying to add a file that has an umlaut in the filename 
1. Navigating to file location on my NAS (WD MyBookLive)
2. Tap on filename (03. Nena - Zurück in die Zukunft.m4a)
3. Get error message (see below).

# 🤔 Expected Results

File should be added.

# 😲 Actual Results

Error message: "Couldn't communicate with a helper application. Try your operation again. If that fails, quit and relaunch the application and try again."

Retrying makes no difference.

Removing umlaut from filename allows it to work fine.

**Comment by GianniCarlo** [comment]
A big of background regarding our integrations with third-parties:
To provide access to third-party file providers, we have an integration basically to the native Files app. The problem is, that Apple has limitations for our type of integration, that is to say that BookPlayer doesn't know what is going on when the Files app screen is shown, we only get notified about the new item(s) after them have been selected and downloaded, before that we are just waiting for iOS to notify the app. The file list display and download interaction when inside the Files app, is responsibility of the file provider (in this case the NAS app if it has one? or the remote connection to the Files app), they have their own integration that lets the Files app know how to display their files and handle the interaction with them.

This can happen with other sources like Dropbox as well, but sadly it's currently out of our hands, due to the app not receiving any actionable events though
