### ISSUE TITLE
Unable to export more than one file at a time

### ISSUE THREAD

**Issue by bkunat** [TortugaPower/BookPlayer#591]
Hi all, 

First of all, I wanted to thank you for all the work. BookPlayer has become my favorite audio player of the last couple of months. 
I'm not entirely sure if this is more of a feature request or a bug. 

# 🗣 Context

The newest version of BookPlayer.app does not support exporting more than one file at a time. Share option is greyed out when more than one file is selected. 

# 💬 Narrative

As a user
I want to export all chapters of a single book at once
So that I can create an outside backup 

_Provide design example, screenshot, text input/output etc_

# ✅ Acceptance Criteria

**GIVEN** Book that consists of multiple chapters
**WHEN** I try to share all chapters at once 
**THEN** I'm able to share it using any method of choice (AirDrop etc)

**Comment by GianniCarlo** [comment]
Hi @bkunat !, we have the building blocks for this with the class `BookActivityItemProvider`. I purposely limited the feature to just exporting one item at a time, due to not being sure what would be the breaking point for exporting a playlist (in terms of sizing or number of items).

If anybody is up for this, please feel free to reach us via [Discord](https://discord.gg/MjCUXgU) and we can point in the right direction 👍
