### ISSUE TITLE
By default, make app theme match system theme

### ISSUE THREAD

**Issue by rakleed** [TortugaPower/BookPlayer#594]
By default, please make the app theme match the system theme. Since this is exactly what is done in the vast majority of other apps, and it is convenient.

**Comment by GianniCarlo** [comment]
This totally makes sense, I'll change this for the next release 👍

**Comment by GianniCarlo** [comment]
This issue is solved in the upcoming [release 4.0.0](https://github.com/TortugaPower/BookPlayer/pull/600/files#diff-1e5ac206acc8a8ac41dbdc5d9f9ea5cb9371fd69a9ff9865f28c185c00759f72R176-R178), see excerpt 

https://github.com/TortugaPower/BookPlayer/pull/600/files#diff-1e5ac206acc8a8ac41dbdc5d9f9ea5cb9371fd69a9ff9865f28c185c00759f72R176-R178

**Comment by rakleed** [comment]
@GianniCarlo I reinstalled the app, and although I have a dark theme on my system, the first time I started the app, the light theme was displayed (while the System theme option was set in the settings). After closing the app and reopening it, a dark theme was displayed.

It would be nice if the app theme matches the system theme the first time you open it.

**Comment by GianniCarlo** [comment]
@rakleed thanks for pointing it out, [this commit](https://github.com/TortugaPower/BookPlayer/pull/613/commits/c49edf0dbd9f4639edf1335d27fd19179ce07e6b) handles that issue and will be included in the next release
