### ISSUE TITLE
Bug: Crashing on launch

### ISSUE THREAD

**Issue by hydrohd** [TortugaPower/BookPlayer#627]
## Environment

 - OS Version: 14.7.1
 - App Version: 4.1.0
 - iPhone XR

## Description

Recently updated my BookPlayer to 4.1.0, the app refuses to launch anymore :( I tap on it and it just returns to home screen.

## Steps to reproduce the behavior
1. Update to latest version of app 
2. Try to launch the app by tapping on it
3. App just refuses to open.

**Comment by GianniCarlo** [comment]
This looks like it's due to a failed migration, I tried to handle this in [this commit](https://github.com/TortugaPower/BookPlayer/commit/71a00e31), to at least reinitialise the library, but it looks like it's not working, maybe due to the library trying to access the core data objects before they're ready. We are currently working on refactoring the app navigation so it uses Coordinators, which will help us among other things, to isolate the database migrations to a specific view (which to be honest, sounds like a good idea to include in 4.2.0 which will have the migration for bookmarks support 🤔)

Right now the only option is to delete and install again :/ sorry about that @hydrohd
