### ISSUE TITLE
Import folder zip

### ISSUE THREAD

**Issue by rastaman111** [TortugaPower/BookPlayer#640]
Hey!  I noticed such a problem, if you create a folder on your computer and upload an audio file and a picture there and then create a zip and then import it into the application, then everything in the folder is imported into the application

![image](https://user-images.githubusercontent.com/15727518/135727878-e331c001-54a3-40db-bb86-a21c9a348765.png)

**Comment by GianniCarlo** [comment]
This is as it's intended, with previous versions we learned that it's a not a great idea to just allow importing mp3/m4b/m4a, because there are other formats like mp4 that actually can be played with our player component [AVPlayer](https://developer.apple.com/documentation/avfoundation/avplayer). So we would rather let everything through, and let the player show the proper error if it can't load the file
