### ISSUE TITLE
Any reason ios file sharing is disabled?

### ISSUE THREAD

**Issue by 0507spc** [TortugaPower/BookPlayer#683]
Is there any reason ios files app sharing has been disabled?

info.plist:

<key>LSSupportsOpeningDocumentsInPlace</key>
	<false/>

can this be made true? Would that cause other issues. Main use would be for adding or saving files previously added.

**Comment by GianniCarlo** [comment]
File sharing via iTunes (or Finder) is enabled already, that key though refers to when importing the files for example via the integration we have with the Files app, we make a copy, instead of accessing directly the file from its source. We don't currently support remote sources, which is one of the reasons we haven't integrated yet with the apple books/music library

For the time being it's easier to just request a copy of the file, import that and handle everything locally. We do eventually want to go beyond that

ps. let me know if I'm misremembering something, it's been a while since I've looked into that part of the docs

**Comment by 0507spc** [comment]
What I mean is the Files app on phone and iPad, to see BookPlayer you need to enable both. Here is the stackoverflow comment I found:

 `The file sharing link included in the question is for the iTunes-based file sharing, which is still supported and requires the UIFileSharingEnabled key only. The new Files app in iOS 11 requires that key plus the LSSupportsOpeningDocumentsInPlace key.`

However, if like you say, this has other implications then it is not worth it. I was just hoping I could "side load" files in and out of a folder directly on the phone.

**Comment by 0507spc** [comment]
This gives details, does seem to be both required:

https://www.appcoda.com/files-app-integration/

No worries if not, just a nice to have. 😃

**Comment by GianniCarlo** [comment]
I've added support for this in the PR #688, thanks for bringing this up @0507spc . This will be released in the next version after v4.2.3 which is being reviewed 👍
