### ISSUE TITLE
Bug: ...Apple Watch app won't connect to the phone at all

### ISSUE THREAD

**Issue by movieman12341** [TortugaPower/BookPlayer#703]
## Environment

 - OS Version: [15.1]
 - App Version: [4.3.0-1]

## Description

My watch says "Connectivity Error. There's a problem connecting to your phone, please try again later."

I've tried deleting Bookplayer from my phone and watch and re installing but nothing works. All functionality on apple watch doesn't work rendering the apple watch app useless as it can't control anything or start playback.

## Steps to reproduce the behavior
1. Download bookplayer to iPhone and apple watch
2. Click on the apple watch app
3. Try to use the apple watch app. For me absolutely nothing works
![incoming-E276D5CE-2CF1-4C1C-97DE-33D564F3E00E](https://user-images.githubusercontent.com/21317547/144267713-2e0b19d1-7a6f-4c2e-9341-ed0b92686a46.PNG)

**Comment by GianniCarlo** [comment]
This is due to [this flag: isReachable](https://developer.apple.com/documentation/watchconnectivity/wcsession/1615683-isreachable) being false. Given that once this flag gets stuck, there's nothing that can change it without doing the next steps, we have removed this check for the next release (there are reports that even if it's false, the messages between the phone and the watch still work)

What has worked for users that have reached out via email, is:
1.- Turn off and on the Apple Watch
2.- Deleting just the BookPlayer Watch app extension from the watch, and reinstalling it from within the iPhone Watch app, without ever deleting the main BookPlayer app from your phone
