### ISSUE TITLE
Bug: ...keeps looping on chapter change

### ISSUE THREAD

**Issue by povlhp** [TortugaPower/BookPlayer#716]
## Environment

 - OS Version: 15.2
 - App Version: latest

## Description

Have a self made m4b. It goes into a 1-2s loop on chapter change. 

## Steps to reproduce the behavior
1. 
2. 
3.

**Comment by SommerEngineering** [comment]
I was just about to open the same issue 😉 

I am also using iOS 15.2 and the new version 4.4.0 of the app.

However, the bug does not consistently occur: Sometimes the app plays a few chapters correctly until it gets stuck in an infinite loop at the end of another chapter. Then it happens that the bug happens with every chapter. It does not help to quit the app completely (via the iOS app switcher). As soon as the app is opened again and the audiobook is continued, the infinite loop starts again.

What I noticed is that even if the app manages to change chapters without an infinite loop, there is another issue. However, this issue is only audible when the speaker does not pause at the end of the chapter and/or there is no pause at the beginning of the next chapter. Then one or two words are repeated in version 4.4.0. Example: The chapter ends with the words "*And then it happened*". If this chapter has no pause at the end, the word "*happened*" is played twice.

What in case of an infinite loop helps, however, is to pause, then turn play back on. Sometimes it works again immediately, other times the pause/play switch has to be repeated two or three times. The bug is unfortunately very annoying: I want to listen to audiobooks in situations where I am not using the smartphone and/or may not have my hands free. For example, when cooking, in the car or in bed. In these cases, I cannot use this workaround 🙁 .

By the way: The previous version 4.3.0 had not this issue; seems to be a regression issue 👍 .

**Comment by povlhp** [comment]
I am like 30 short chapters into this book, around 2h30 before it happened. 
Have had success once with reboot. 
But force quit app and relaunch does not fix it. 
So almost looks like stored state at play. 
But problem is around chapter change only. 


Sendt fra min iPhone

**Comment by GianniCarlo** [comment]
I just experienced this as well with an m4b, I'll take a look and see if I can release a hotfix next week. Have anybody had problems with the new bound/volume feature for mp3s?

in the meantime I've had to stop playback, and skip to the next chapter manually :/

**Comment by SommerEngineering** [comment]
Sorry @GianniCarlo, I only use `*.m4b`.

**Comment by neoofoox** [comment]
I have the same issue. I recorded it, maybe it helps. The problem happens at the end of some chapters.

If I press -30sec and this chapter is finished, it stucks again. So with this chapter I can reproduce it. 

https://user-images.githubusercontent.com/4437437/146693780-0a5dd5bc-f871-47c3-9aef-13ac93cff12a.MOV

BookPlayer 4.4.0-8
iPhone 12 Pro - iOS 15.2

**Comment by GianniCarlo** [comment]
#720 fixes the issue, it turns out the for the mp3 volumes, we added a load-item on chapter change, but that it's not needed for m4b, since it's a single file

**Comment by SommerEngineering** [comment]
Good job @GianniCarlo 🙂 Do you think we can expect a hotfix release this week as a christmas present 😉 ?

**Comment by GianniCarlo** [comment]
I submitted the new version for review 🙌 , it usually takes 2-3 days for Apple to review a version, but they did warn us that it will take more time for review because of the holidays. Let's hope it gets released this week 😁 

![Screen Shot 2021-12-20 at 8 31 25 AM](https://user-images.githubusercontent.com/14112819/146774778-338959a3-515d-4080-b5c3-1b64771c3784.png)

**Comment by GianniCarlo** [comment]
v4.4.1 was just released to the appstore, please let us know @SommerEngineering @neoofoox @povlhp  when you get to test the new version

**Comment by neoofoox** [comment]
Tested the chapter shown in the video. It works now. 
Playing audiobook for 30 minutes now without issues. 👍

**Comment by SommerEngineering** [comment]
@GianniCarlo Thanks, it work‘s just fine 🙂 👍 Good work. Thanks also for the fast support 😀

**Comment by GianniCarlo** [comment]
Thanks for the confirmation guys!
