### ISSUE TITLE
Bug: Multiple problems when displaying the BookPlayer UI via CarPlay.

### ISSUE THREAD

**Issue by fabifabulousity** [TortugaPower/BookPlayer#738]
## Environment

 - OS Version: 15.2.1
 - App Version: 4.4.2-2

## Description

Bug when displaying the BookPlayer UI via CarPlay.

The iPhone is connected to CarPlay via Lightning. BookPlayer is opened via CarPlay. The following problems occur:
- Icons of the "Library" and "Recent" tabs are sometimes not displayed (replicable when BookPlayer is closed and reopened several times, or when switching between other apps and BookPlayer in the CarPlay UI).
![IMG_3316](https://user-images.githubusercontent.com/72652159/149618897-046e6fee-a746-4f9c-8bdb-6d3bd39a31e5.jpeg)
 
- Error message "Connection to BookPlayer not possible".
![IMG_3318](https://user-images.githubusercontent.com/72652159/149618926-b5e4487b-21f5-49e4-a6fb-aa3978390293.jpeg)

- The titles in the library are not displayed at all
![IMG_3320](https://user-images.githubusercontent.com/72652159/149618935-9eba8103-43d6-4d3c-8bb4-8f054a4b5493.jpeg)

- The titles in the library are displayed without the audio book cover.
![IMG_3322](https://user-images.githubusercontent.com/72652159/149618941-81cdacec-067f-440e-84e4-5cace5593b29.jpeg)

Meanwhile, the App on the iPhone behaves normally, displaying all library titels, controls etc. 
![IMG_3321](https://user-images.githubusercontent.com/72652159/149618964-ee0e7995-9822-426e-b93f-bc26919f1255.jpeg)

## Steps to reproduce the behavior
1. Connect iPhone to Car via Lightning Cable => CarPlay UI opens
2. Open BookPlayer App within CarPlay
3. Switch between multiple CarPlay Apps and go back to BookPlayer App

**Comment by fabifabulousity** [comment]
Unfortunately these issues with CarPlay happen very frequently, so it is not possible at even start playing an audiobook (when there is only a empty library screen, see first screenshot). That’s a bit frustrating. Do you have any idea why that is or if you are able to fix it?

**Comment by pichfl** [comment]
Can confirm at least some of these. 

That being said, debugging and fixing CarPlay is a very painful process. The simulator gets you only this far which means I or others working on this have to cram into their car and debug wirelessly as at least my car supports wired CarPlay only. 

Besides the weird looks you get from passers-by, development in that state is just very cumbersome.  

So is pushing an open source issue further up. Please do not do this unless you are willing to contribute. We are trying our best and pour our free time and resources into this project and you get a free app out of it. The only valid way to demand increased development speed is by downloading Xcode, learning Swift, start debugging and demand that from yourself. 

Otherwise: We'll look into it when there is time to and when I'm no longer freezing to my steering wheel while debugging in a curb side parked car.

**Comment by Dev-Josue** [comment]
Not sure if I am missing something here but I just wanted to say that I too have experienced this issue. 

Overall this is a very competent bug report. While I understand that development has its challenges, the response is very aggressive. 

As a user of this app and a member of a software development team I hope you will take it under advisement to appreciate errors being identified and communicated and not take them as criticism. 

Book player is a great app and it sounds like a passion project. I hope in the future you can find time to resolve this issue but it is definitely not a high priority bug as the app can function on the phone. 

That being said you mentioned learning swift and debugging the issue. If I attempted to debug it, is swift the predominant language used to code this app? I hope a fork can be acceptable in the future and maybe I can help with finding a solution.

**Comment by Dev-Josue** [comment]
Wow that's awesome. I appreciate all the work, effort and care your dev team puts into this amazing app. I have enrolled in Bookplayer plus to show my support and appreciation. Thank you!

**Comment by GianniCarlo** [comment]
I think the new functionality is ready for testing 🤔, though I cannot upload a beta yet, because Apple requires us to request again access to CarPlay for the new APIs (hopefully we hear back from them soon), but in the meantime here's a video of the new functionality in the simulator

The now playing screen now has:
- Chapter skip controls
- Bookmark creation
- Chapter list
- Playback controls: boost volume and speed change (due to lack of interface elements, we had to do 0.1 increments here and put the whole list from 0.5 to 4)

ps. nevermind that it fails to resume playback in the simulator, after a while, the files imported there get cleaned up by the OS 🤷‍♂️

This also solves #509 #501 and possibly #481


https://user-images.githubusercontent.com/14112819/160850700-96ec282a-55b9-4385-b3d4-7cc553f84312.mov

**Comment by GianniCarlo** [comment]
It's finally out in the AppStore! (in the latest release v4.6.0)

**Comment by Dev-Josue** [comment]
Thank you so much. It looks amazing! It’s very responsive and I love the features. Thank you for creating such an awesome app!
