### ISSUE TITLE
Bug: ...First second of chapter is being skipped

### ISSUE THREAD

**Issue by procion1302** [TortugaPower/BookPlayer#768]
## Environment

OS Version: 15.3.1
App Version: 4.4.5-2

## Description
First second is being skipped, when starting a new chapter of a multichapter book.

## Steps to reproduce the behavior
1. Create multichapter book.
2. Start listening the first chapter
3. When the second chapter starts to play, it skips the first second of the next chapter
4. If now we rewind the second chapter to the start using progress bar, audio starts from the beginning properly

**Comment by dhamaniasad** [comment]
I get this too. Whenever a chapter changes the first (or maybe first few) seconds are skipped. Leads to a very jarring experience.

**Comment by rh63** [comment]
Can confirm this behavior. I can't remember in which update that bug had its first appearance, but it is very annoying.

If that helps: All my audio books are in mp3 format (many separate files) which I tagged myself; including cover artwork (1000x1000 px max, size < 1 MB).

**Comment by GianniCarlo** [comment]
@rh63 can you share via email 3 of the files where this is happening? for testing purposes 👍

**Comment by rh63** [comment]
2nd attempt: The first try failed because the github mail system refuses 
to accept attachments with a size > 10 MB.
You can find the three files here: 
<https://1drv.ms/u/s!AskXjJro-MyYke5MrjKCdGJc4qIspw>. Sorry for the 
inconvenience! 🤷‍♂️

------------------------------------------------------------------------

Hi Gianni,


no problem. Attached there are 3 consecutive files of an audio book. The 
tagging was made with mp3tag (<https://www.mp3tag.de/en/index.html>).

Good luck! 😊 If you need any more information or tests, let me know.

Cheers!
Ralph

------------------------------------------------------------------------
*Von:* Gianni Carlo ***@***.***
*Gesendet:* Dienstag, 28. Juni 2022, 13:40
*An:* TortugaPower/BookPlayer
*Cc:* Ralph; Mention
*Betreff:* [TortugaPower/BookPlayer] Bug: ...First second of chapter is 
being skipped (Issue #768)

> @rh63 can you share via email 3 of the files where this is happening? 
> for testing purposes 👍
>
>
>

**Comment by GianniCarlo** [comment]
Files downloaded 👌 thanks @rh63 ! I'll test later today and see what I can find

**Comment by arku1** [comment]
I have same issue, when next chapter ie next file starts to play it jumps random amount of seconds forward from the beginning, sometimes might be 1-2 mins. 
My audiobooks are usually mp3 files.

**Comment by GianniCarlo** [comment]
This is solved in 4.7.1 (with the problem of mp3 volume stopping, which should be solved in 4.7.2 pending appstore approval for release)
