### ISSUE TITLE
Bug: Progress bar not accounting for speed change

### ISSUE THREAD

**Issue by andrewp24** [TortugaPower/BookPlayer#782]
## Environment

 - OS Version: 15.4.1
 - App Version: 4.4.5-2

## Description

The progress bar and % read do not seem to account for the speed changes. It looks like the bar/% look at the original time the book should take at 1x speed. The iOS notification pane, to me, looks more accurate.

## Steps to reproduce the behavior
1. Play any book
2. To see clearly, go to around half way through a book with it set to 1x
3. Change to a speed such as 2x. Your position should be closer to the end as your % through the book is in a way further along.

See photos for reference.

![image](https://user-images.githubusercontent.com/9084662/161799282-3fde3d2f-3261-40e1-9c23-38b7ec939d67.png)

![image](https://user-images.githubusercontent.com/9084662/161799915-8cd65cb5-810a-4aa6-a441-0db813dccf4b.jpeg)

**Comment by andrewp24** [comment]
Thinking more about it, I feel like it could go either way? Like if I'm at 50% of a 10hr book at 1x, I should obviously be at 50% progress. But then if I shifted that to 2x, while I'm still at 50% time wise from the beginning, my rate makes it like I'm at 75%.

**Comment by GianniCarlo** [comment]
Hi @andrewp24 ! yes, the progress bar and percentage are from the current time point of view, whereas the progress on the system, seems to be more aligned to the remaining time instead. There's something weird there though, if you drag from the control center, you'll notice that it jumps after you drop it, so maybe we're setting the metadata of the now playing in the system incorrectly? I have to do some tests, because when we introduced displaying the correct remaining time depending on the speed rate, this was also modified

<img width="808" alt="Screen Shot 2022-04-07 at 07 00 47" src="https://user-images.githubusercontent.com/14112819/162193989-46d78b83-b192-4c89-b617-9cad66ee6349.png">

**Comment by andrewp24** [comment]
Understood, and yes that is interesting, didn't notice that jump but do after you mentioned it. Thanks for taking a look at this!

**Comment by GianniCarlo** [comment]
I've looked further into this, I do think that we have to keep the progress % in relation to the current time, that is to day, if I'm at 5h of a 10h book, no matter the speed, the progress % should be 50%, having said that, there's a bug in the control center with a simple solution, right now it's messing up the progress % when it's showing the remaining time in-app, and that's because it's using the reduced total duration of the book, instead of using the unmodified total duration of the book.

Now the second problem that I found, and it's related to this issue, is that when you drag and seek on the control center, when you drop the slider in a new place, the app doesn't get a % back from that event, instead we get a time we should jump to, the problem here is that to properly display in the control center the remaining time based on the speed selected, we have to set the duration property to the remaining total (in relation to the speed), which modifies the 'available time' to jump to. For example, let's say you start a new book of 8h duration, so at the beginning there's 8h remaining time in the book, if you're on 2x speed, the app and the control center will display 4h remaining, the difference is that in the app we handle the slider % wise, while the control center we don't really have control over it, we just provide the current time and the duration to the OS, and the OS provides the knob in the control center, which can now only go from 0 to 4h instead of 8h

**Comment by GianniCarlo** [comment]
I think we can safely ignore the second behavior, since on the day to day it's usually smaller jumps, we can revise this in the future if it's really a problem, but nobody has reported it yet, also it's worth noting that with the current APIs for the control center, we cannot overcome this limitation, and having a different remaining time between the in-app player, and the control center will be a lot more confusing for users 🤔

**Comment by GianniCarlo** [comment]
I'm closing this issue for the time being, setting the properties `MPNowPlayingInfoPropertyElapsedPlaybackTime` and `MPMediaItemPropertyPlaybackDuration ` is what determines how the OS shows the progress in the control center, and to properly reflect the remaining time (considering speed) both in-app and in control center, we have to set the duration to a lower time than the total duration of the book (or chapter). When or if iOS decides to change this behavior, and use `MPNowPlayingInfoPropertyPlaybackProgress` instead to show the progress slider in the control center, and dragging from there returns a percentage instead of a point in time, then we can update and solve this. For the time being, we have to choose between consistent remaining time or consistent knob placement in the slider, and I think it's better to choose consistent remaining time
