### ISSUE TITLE
Repeat / loop feature

### ISSUE THREAD

**Issue by jhunschejones** [TortugaPower/BookPlayer#807]
## Feature request
I'd love to have a feature that lets me put a single book or Volume on repeat, rather than auto-advancing to the next book. I use BookPlayer to listen to target language books for language learning, and this would help me focus on one book at a time.

## Narrative

**GIVEN:**
A user with several audio books or volumes indicates they would like to play one on loop / repeat
**WHEN:**
...the setting is enabled and an audio book or volume finishes 
**THEN:** 
...the same audio book or volume starts again from the beginning

## Design

This feature exists in lots of media player apps, often accessible to a user through a "repeat all" and "repeat one" button:

<img width="620" alt="Screen Shot 2022-06-22 at 3 57 35 PM" src="https://user-images.githubusercontent.com/34409939/175134779-beb11546-3601-4c72-ae9a-a9ddba7fb96b.png">

**Comment by GianniCarlo** [comment]
This is finally out in v5.4.2, the UI is a bit more rudimentary (an option in the 'More' options in the player screen). I did it this way because when the Player UI was made, it was done with Storyboards, which is no longer something that Apple recommends to developers, and I don't want to sink more code than I need to into UIKit components (the goal being to move the project to a SwiftUI only app)
