### ISSUE TITLE
Bug: ...Importing Audiobook Only Imports 1st Chapter

### ISSUE THREAD

**Issue by Barmaid9201** [TortugaPower/BookPlayer#811]
## Environment

 - OS Version: [iOS 16.0]
 - App Version: [4.6.1-1]

## Description

I am attempting to import an audiobook in mp3 container, however, after moving the file through Finder on my mac, Bookplayer does find it and asks to import, once I do that, it only seems to import the first chapter. I tested the file and played it and sure enough it's the whole audiobook (I merged all of the parts into a single mp3). I tried using Forecast to see if there were Chapter markers but it doesn't seem like there are any. 

## Steps to reproduce the behavior
1. Merge mp3 files into a single mp3 file using Merge MP3 from Shchuka
2. Plug iPhone into MacBook
3. Drag and Drop newly combined mp3 file into iPhone via finder (Finder > iPhone > Files > BookPlayer)
4. Wait for BookPlayer to ask to import. When the popup appears, hit import.

**Comment by GianniCarlo** [comment]
Hi @Barmaid9201 ! I'm not sure I understand fully the scenario here, the problem is that the app only shows the metadata for the first chapter, but actually the entire audiobook is there? if that's the case, it sounds like Shchuka is not adding the chapter markers, so BookPlayer only reads what Shchuka encoded into the result file 🤔, please correct me if I read things wrong. You could also just import the entire list of mp3s, and use the Combine into volume feature when importing, so the app will treat the files as a single book with chapter marks

ps. since you have a MackBook, I think it's far easier to just airdrop the files to your iPhone (right click on selected files → share → airdrop → select your iphone), so you don't have to go through the hassle of connecting the iPhone, go trough Finder and drag and dropping the files

**Comment by Barmaid9201** [comment]
Hey @GianniCarlo Yes, I think you have it correct. After I import the file, and look at it in the "Library" in BookPlayer, it only imports the first chapter (the first chapter runtime is displayed below the "Author Name"), and when I go to play the file, sure enough, it will only play the first chapter (about 15 seconds). When I go to the find the file in my phone (Files >Browse > On My iPhone > BookPlayer > Processed) I see the file, and it is in fact the full sized mp3. When I copy that file back to my computer and try to play it with any media player, it is able to play the whole thing. 

Adding another wrench into the works is, I have been able to do this exact process in the past (including the Merge step with Merge MP3 from Shchuka) and have not had the same issue at all. The source for these audiobooks has changed, but the process of converting/merging, transferring, and importing them is the exact same. The only difference as far as I can tell is that the old versions that worked were Stereo, while this version that doesn't work is Mono. Other than that, they are nearly identical. 

PS. Thank you so much for helping me troubleshoot this

**Comment by Barmaid9201** [comment]
Hey @GianniCarlo I fixed it! Apparently there were issues with the headers of the audiobook file ("Wrong number of MPEG frames specified in Xing Header" and "Wrong number of data bytes specified in Xing Header"). I used MP3val to scan the files and then repair the problems. Once that was done, I followed my usual routine and sure enough it worked. Once again, thanks for your help!

**Comment by GianniCarlo** [comment]
I'm glad you found a solution @Barmaid9201 🙌 , also thanks for pointing out MP3val, it looks like a much simpler option than recommending users to use FFMPEG and ffprobe to analize their files 😅
