### ISSUE TITLE
Sleep timer reset by pressing play

### ISSUE THREAD

**Issue by ferdinandea** [TortugaPower/BookPlayer#822]
## Feature request

- If the Sleep timer comes to the end, and I am not falling asleep, i want to continue with a new Sleep timer interval by pressing play on my headphones

## Narrative

- Feel free to change the following format to better suit the details of the enhancement

**GIVEN:**
- Sleep timer pause the audiobook
**WHEN:**
- I press play on my headphones 
**THEN:** 
- The player continues with playing in a new sleep timer interval

**Comment by Cptbluetooth** [comment]
A feature of an Android audiobook app I used to use was similar to what you’re looking for. You could reset the sleep timer by moving your phone. Each time you just lifted and put the phone back down it would restart the timer interval you had picked. It was nice since, like pressing the headphone button, it required no phone interaction.

**Comment by GianniCarlo** [comment]
This is now live on the AppStore in v5.2.0, Settings → Player Controls → Auto  Sleep Timer, it will restart the last active sleep timer when resuming playback
