### ISSUE TITLE
Playback stops 

### ISSUE THREAD

**Issue by mexxBf** [TortugaPower/BookPlayer#844]
Hi,

I would like to report that the playback bug is still there in 4.7.1-2 and iOS 16.

At first it worked, but it appeared again.

Maybe its related to Airplay? At least I use it a lot with it.

Is it possible to add some more information for you?

Thank you

Edit: Its not related to Airplay. It stops with playback on the iphone as well.

**Comment by GianniCarlo** [comment]
damn :/, @mexxBf hmmm next question would be, does it reliably happen between two specific chapters? if so, could you share the two files with me? and if there's any specific playback speed?

For more info, this bug started happening when I removed the +0.5 added as a buffer to a chapter start, which was making chapters start awkwardly for some audiobooks. At this point, I think that is preferable than having playback stop, but ideally we can solve this in the next patch version

**Comment by GianniCarlo** [comment]
alright I found the root issue, when one audio file ends, there's a callback that is triggered by the `AVPlayer`, but this only happens if it reaches truly the last available time of the file (e.g. for a file of duration 100.005, and current time 100 the callback won't be triggered until it reaches 100.005). The app was depending on this callback for mp3 volumes to trigger the continue playback, so it seamlessly continues with the next audio file, but here comes a problem with floating points in programming, where we were loading the next chapter when we thought the current time was already in the next chapter, but the previous chapter never truly ended (there were these micro seconds at the end)

The solution shipped on v4.7.1 was about truncating these floating values to 5 decimal places, in the hopes that it will align, but that's not the proper solution, as the finished callback still wouldn't be reliably called. So the solution now would be to just use these values as a reference point to display chapter information, or load the proper chapter when jumping in time, otherwise let the audio file end, and on the callback perform the load of the next chapter if it's necessary

I'll test this out for a bit and put up a beta on the weekend 👍

**Comment by mexxBf** [comment]
I'm sorry I didn't respond. My little toddler leaves zero time to do other things right now 🙈 I'm very glad you found the issue. My wife and me are relying on this app right now 😂

**Comment by GianniCarlo** [comment]
@mexxBf don't worry about it 😁, right now the changes are in `develop`, I submitted a new version, so it should be up by Tuesday probably 👍

**Comment by GianniCarlo** [comment]
This looks to be solved in v4.7.2 which is available in the appstore, feel free to post back if the issue persists

**Comment by 1209090** [comment]
I was about to write that I had a similar issue, but decided to try reinstalling the app and it helped. Just in case if someone else has such a problem. :)
