### ISSUE TITLE
Bug: Battery drain while listening

### ISSUE THREAD

**Issue by CapoD** [TortugaPower/BookPlayer#863]
## Environment

 - OS Version: 16.2 (20C64)
 - App Version: 4.7.2-1

## Description

While listening to audio books the iPhone is heating up and BookPlayer is draining huge amounts of battery. When pausing the playback the iPhone is cooling down again to normal temperature. 

## Steps to reproduce the behavior
1. Listen to random audio book.
2. Wait a few minutes.

**Comment by Gerk** [comment]
iPhone 13 mini, iOS 16.6. BookPlayer 5.0.7-3.

I'm having the same issues with almost all the files I'm trying to play. BookPlayer can chew through my whole battery with a 100% charge within 1.5 hours. Phone gets so hot that the battery won't charge. I can provide audio file samples if it's helpful or any other debugging information. Hopefully this gets addressed sooner than later. In the meantime I guess I'll have to find another app, which is a shame because aside from the massive CPU usage that app is fantastic!

**Comment by GianniCarlo** [comment]
I'm closing this issue in favor of ticket #843 to consolidate all the info and have one place where I can follow up with updates
