### ISSUE TITLE
can't "Select all" when browsing files from MEGA

### ISSUE THREAD

**Issue by AddaxSoft** [TortugaPower/BookPlayer#870]
title. 

![image](https://user-images.githubusercontent.com/6898938/214305021-b883b889-164f-42ca-94bb-bd89a5cf9bd2.png)

**Comment by GianniCarlo** [comment]
It looks like a problem with Mega's integration to the Files app, instead of just pushing the screen with the list of contents to use the same interface and options from the Files app, it presents a modal screen with their own interface, so that's why there's no Select all option, and will remain that way until they update either their integration or their UI
