### ISSUE TITLE
Bug: ...

### ISSUE THREAD

**Issue by mifranc** [TortugaPower/BookPlayer#949]
## Environment

 - OS Version: [e.g. 13.5.1] iOS 15.7.6 (iPhone 7)
 - App Version: [e.g. 3.9.0-1] 4.7.2-1

## Description
Fast battery drainage: I want to corroborate the similar bug posts (e.g.#884): I have the same issue on my iPhone 7. I have been using PocketCast app on this phone a lot for many months similarly mostly playing through the iPhone's speaker without using earphones, and I have never experienced quick battery draining or device warming of this extent with it. Could it depend also on the file size perhaps? Podcast episodes are small compared to the couple of hundred MB or even above GB size M4B audiobooks. Usually I convert them from multiple mp3 files with the "AudiobookConverter" Windows program. 
Battery drainage e.g. today: more than 10% after half an hour with locked phone screen +with max. volume through phone speaker. The battery is not new but ine.g. today: Bookplayer 36min screen+1h 4' background=65% of the total battery drain, Pocket Casts: 11' screen+52' backgd= 21%
Other than this (and the smaller bug of not stopping playback at the 'end of current chapter' timer), I am grateful for this app, a great set of functionality and usability, thank you!

## Steps to reproduce the behavior
1. playing m4b audiobooks with chapters
2. 
3.

**Comment by rstewa** [comment]
I'm having the same issue on my iPhone 14 Pro Max

**Comment by mguertin-jump** [comment]
I'm having the same issues with almost all the files I'm trying to play.  iPhone 13 mini, iOS 16.6.  BookPlayer 5.0.7-3.  BookPlayer can chew through my whole battery with a 100% charge within 1.5 hours.  Phone gets so hot that the battery won't charge.  I can provide audio file samples if it's helpful or any other debugging information.  Hopefully this gets addressed sooner than later.  In the meantime I guess I'll have to find another app, which is a shame because aside from the massive CPU usage that app is fantastic!

**Comment by Gerk** [comment]
iPhone 13 mini, iOS 16.6. BookPlayer 5.0.7-3. 

I'm having the same issues with almost all the files I'm trying to play. BookPlayer can chew through my whole battery with a 100% charge within 1.5 hours. Phone gets so hot that the battery won't charge. I can provide audio file samples if it's helpful or any other debugging information. Hopefully this gets addressed sooner than later. In the meantime I guess I'll have to find another app, which is a shame because aside from the massive CPU usage that app is fantastic!

**Comment by GianniCarlo** [comment]
I'm closing this issue in favor of ticket #843 to consolidate all the info and have one place where I can follow up with updates
