### ISSUE TITLE
Bug: Book resets to 0:00 after using sleep timer

### ISSUE THREAD

**Issue by tom-kaufman** [TortugaPower/BookPlayer#955]
## Environment

 - OS Version: 16.1
 - App Version: 5.0.0-10

## Description

After the sleep timer expires, the book is back at the very beginning. I happened two nights in a row now. 

## Steps to reproduce the behavior
1.  Set 30 minute timer
2. Fall asleep listening
3. The next day, the book is at 0:00

**Comment by GianniCarlo** [comment]
Hi @tom-kaufman! I think this is related to an issue with the socket, where it was connecting, but the sync events weren't reaching the server, this is fixed in the latest version currently available on the AppStore (v5.0.3).

Let me know if you don't have cloud sync enabled, as that would be another scenario completely 🤔

**Comment by tom-kaufman** [comment]
I realized that I was on an old version only after creating this issue. It indeed is fixed with 5.0.3. And yes, I was using cloud sync. Thanks for the prompt response!
